In [3]:
# Import Pandas and display the installed Pandas version.
# Check whether Pandas is installed
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [4]:
# Create a Pandas Series with monthly electricity usage.
monthly_units = pd.Series(
    [420, 385, 510, 465, 590],
    index=["March", "April", "May", "June", "July"],
    name="Electricity_Units"
)

monthly_units

March    420
April    385
May      510
June     465
July     590
Name: Electricity_Units, dtype: int64

In [5]:
# Access a Series value by label and by position.
print("May usage:", monthly_units["May"])
print("First month's usage:", monthly_units.iloc[0])

May usage: 510
First month's usage: 420

In [6]:
# Create an attendance Series and calculate its average.
attendance = pd.Series([92, 78, 85, 96, 73], name="Attendance")

print(attendance)
print()
print("Average attendance:", attendance.mean())

0    92
1    78
2    85
3    96
4    73
Name: Attendance, dtype: int64

Average attendance: 84.8

In [7]:
# Create a DataFrame containing student details and scores.
students = pd.DataFrame({
    "Student_ID": ["ST101", "ST102", "ST103", "ST104", "ST105"],
    "Name": ["Anitha", "Rahul", "Priya", "Karthik", "Meena"],
    "Course": ["Python", "Python", "AIML", "AIML", "Python"],
    "Attendance": [92, 78, 88, 95, 81],
    "Assessment_Score": [84, 69, 91, 87, 76],
    "Placed": ["Yes", "No", "Yes", "Yes", "No"]
})

students

  Student_ID     Name  Course  Attendance  Assessment_Score Placed
0      ST101   Anitha  Python          92                84    Yes
1      ST102    Rahul  Python          78                69     No
2      ST103    Priya    AIML          88                91    Yes
3      ST104  Karthik    AIML          95                87    Yes
4      ST105    Meena  Python          81                76     No

In [8]:
# Create a DataFrame containing product sales data.
sales_data = pd.DataFrame({
    "Product": ["Laptop", "Monitor", "Keyboard", "Mouse"],
    "Units_Sold": [12, 18, 35, 42],
    "Price": [55000, 18000, 2500, 900]
})

sales_data

    Product  Units_Sold  Price
0    Laptop          12  55000
1   Monitor          18  18000
2  Keyboard          35   2500
3     Mouse          42    900

In [9]:
# Create a DataFrame from a list of order dictionaries.
transactions = [
    {"Order_ID": "ORD001", "Customer": "Arun", "Amount": 2450, "Status": "Delivered"},
    {"Order_ID": "ORD002", "Customer": "Divya", "Amount": 1890, "Status": "Shipped"},
    {"Order_ID": "ORD003", "Customer": "Naveen", "Amount": 4200, "Status": "Delivered"},
    {"Order_ID": "ORD004", "Customer": "Keerthi", "Amount": 950, "Status": "Cancelled"}
]

orders = pd.DataFrame(transactions)
orders

  Order_ID Customer  Amount     Status
0   ORD001     Arun    2450  Delivered
1   ORD002    Divya    1890    Shipped
2   ORD003   Naveen    4200  Delivered
3   ORD004  Keerthi     950  Cancelled

In [10]:
# Create a DataFrame by combining two Pandas Series.
customer_series = pd.Series(["Arun", "Divya", "Naveen"], name="Customer")
amount_series = pd.Series([2450, 1890, 4200], name="Amount")

customer_orders = pd.DataFrame({
    "Customer": customer_series,
    "Amount": amount_series
})

customer_orders

  Customer  Amount
0     Arun    2450
1    Divya    1890
2   Naveen    4200

In [11]:
# Display the complete students DataFrame.
# Inspect the complete DataFrame
students

  Student_ID     Name  Course  Attendance  Assessment_Score Placed
0      ST101   Anitha  Python          92                84    Yes
1      ST102    Rahul  Python          78                69     No
2      ST103    Priya    AIML          88                91    Yes
3      ST104  Karthik    AIML          95                87    Yes
4      ST105    Meena  Python          81                76     No

In [12]:
# Display the row index of the students DataFrame.
# See the default row index
students.index

RangeIndex(start=0, stop=5, step=1)

In [13]:
# Display the first five rows of the DataFrame.
# First 5 students
students.head()

  Student_ID     Name  Course  Attendance  Assessment_Score Placed
0      ST101   Anitha  Python          92                84    Yes
1      ST102    Rahul  Python          78                69     No
2      ST103    Priya    AIML          88                91    Yes
3      ST104  Karthik    AIML          95                87    Yes
4      ST105    Meena  Python          81                76     No

In [14]:
# Display the first three rows of the DataFrame.
# First 3 students
students.head(3)

  Student_ID    Name  Course  Attendance  Assessment_Score Placed
0      ST101  Anitha  Python          92                84    Yes
1      ST102   Rahul  Python          78                69     No
2      ST103   Priya    AIML          88                91    Yes

In [15]:
# Display the last five rows of the DataFrame.
# Last 5 students
students.tail()

  Student_ID     Name  Course  Attendance  Assessment_Score Placed
0      ST101   Anitha  Python          92                84    Yes
1      ST102    Rahul  Python          78                69     No
2      ST103    Priya    AIML          88                91    Yes
3      ST104  Karthik    AIML          95                87    Yes
4      ST105    Meena  Python          81                76     No

In [16]:
# Display the last two rows of the DataFrame.
# Last 2 students
students.tail(2)

  Student_ID     Name  Course  Attendance  Assessment_Score Placed
3      ST104  Karthik    AIML          95                87    Yes
4      ST105    Meena  Python          81                76     No

In [17]:
# Display the shape, columns, index, and data types of the DataFrame.
print("Shape:", students.shape)
print("Columns:", students.columns)
print("Index:", students.index)
print("Data Types:")
print(students.dtypes)

Shape: (5, 6)
Columns: Index(['Student_ID', 'Name', 'Course', 'Attendance', 'Assessment_Score',
       'Placed'],
      dtype='object')
Index: RangeIndex(start=0, stop=5, step=1)
Data Types:
Student_ID          object
Name                object
Course              object
Attendance           int64
Assessment_Score     int64
Placed              object
dtype: object

In [18]:
# Get and display the number of rows and columns.
rows, columns = students.shape

print("Number of students:", rows)
print("Number of columns:", columns)

Number of students: 5
Number of columns: 6

In [19]:
# Create an e-commerce DataFrame and inspect its basic structure.
# E-commerce dataset
ecommerce = pd.DataFrame({
    "Order_ID": ["A1001", "A1002", "A1003", "A1004", "A1005", "A1006"],
    "Customer_Age": [24, 31, 27, 42, 35, 29],
    "Product_Category": ["Electronics", "Fashion", "Electronics", "Home", "Fashion", "Books"],
    "Order_Value": [45999, 2499, 32999, 7800, 3199, 899],
    "Payment": ["UPI", "Card", "EMI", "UPI", "Card", "Cash"],
    "Delivered": [True, True, False, True, True, False]
})

print("Shape:", ecommerce.shape)
print("\nColumns:")
print(ecommerce.columns)

print("\nIndex:")
print(ecommerce.index)

print("\nData types:")
print(ecommerce.dtypes)

print("\nFirst 3 records:")
print(ecommerce.head(3))

print("\nLast 2 records:")
print(ecommerce.tail(2))

Shape: (6, 6)

Columns:
Index(['Order_ID', 'Customer_Age', 'Product_Category', 'Order_Value',
       'Payment', 'Delivered'],
      dtype='object')

Index:
RangeIndex(start=0, stop=6, step=1)

Data types:
Order_ID            object
Customer_Age         int64
Product_Category    object
Order_Value          int64
Payment             object
Delivered             bool
dtype: object

First 3 records:
  Order_ID  Customer_Age Product_Category  Order_Value Payment  Delivered
0    A1001            24      Electronics        45999     UPI       True
1    A1002            31          Fashion         2499    Card       True
2    A1003            27      Electronics        32999     EMI      False

Last 2 records:
  Order_ID  Customer_Age Product_Category  Order_Value Payment  Delivered
4    A1005            35          Fashion         3199    Card       True
5    A1006            29            Books          899    Cash      False

In [ ]:
# Read the Sales CSV file into a DataFrame.
df = pd.read_csv(r"Sales.csv")

df

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
1,10002,1194,Customer_1120,Bengaluru,North,Business,Camera,Product_023,Online,Debit Card,...,15,2.0,10.0,22,2025-10-15,41597.03,6239.55,35357.48,False,Normal
2,10003,1164,Customer_1247,Pune,South,Professional,Headphones,Product_022,Online,UPI,...,20,3.0,13.0,56,2025-12-28,5869.60,1173.92,4695.68,False,Slow
3,10004,1110,Customer_1191,Bengaluru,North,Teacher,Mouse,Product_011,Partner,Credit Card,...,5,1.1,11.0,29,2025-07-29,117873.48,5893.67,111979.81,True,Slow
4,10005,1109,Customer_1163,Trichy,Central,Teacher,Keyboard,Product_001,Partner,Debit Card,...,20,1.0,4.0,21,2025-10-04,364887.25,72977.45,291909.80,True,Fast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1207,10831,1062,Customer_1139,Mumbai,Central,Business,Headphones,Product_021,Mobile App,Debit Card,...,10,4.2,1.0,63,2025-12-09,355710.45,35571.04,320139.41,True,Fast
1208,10751,1241,Customer_1229,Pune,North,Teacher,Printer,Product_051,Partner,Cash,...,0,4.8,8.0,34,2025-07-27,394035.55,0.00,394035.55,True,Normal
1209,10047,1112,Customer_1215,Pune,North,Freelancer,Mobile,Product_012,Store,Credit Card,...,20,2.1,12.0,46,2025-12-05,105552.08,21110.42,84441.66,False,Slow
1210,11133,1199,Customer_1068,Chennai,Central,Professional,Printer,Product_058,Mobile App,Credit Card,...,30,2.9,8.0,41,2025-12-12,20187.00,6056.10,14130.90,False,Normal
1211,10129,1144,Customer_1169,Chennai,West,Student,Monitor,Product_032,Partner,Cash,...,5,2.1,12.0,37,2025-09-06,167883.65,8394.18,159489.47,True,Slow

In [22]:
# Check the data type of the DataFrame.
type(df)

pandas.core.frame.DataFrame

In [23]:
# Display the first rows of the sales DataFrame.
df.head()

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
1,10002,1194,Customer_1120,Bengaluru,North,Business,Camera,Product_023,Online,Debit Card,...,15,2.0,10.0,22,2025-10-15,41597.03,6239.55,35357.48,False,Normal
2,10003,1164,Customer_1247,Pune,South,Professional,Headphones,Product_022,Online,UPI,...,20,3.0,13.0,56,2025-12-28,5869.60,1173.92,4695.68,False,Slow
3,10004,1110,Customer_1191,Bengaluru,North,Teacher,Mouse,Product_011,Partner,Credit Card,...,5,1.1,11.0,29,2025-07-29,117873.48,5893.67,111979.81,True,Slow
4,10005,1109,Customer_1163,Trichy,Central,Teacher,Keyboard,Product_001,Partner,Debit Card,...,20,1.0,4.0,21,2025-10-04,364887.25,72977.45,291909.80,True,Fast

In [24]:
# Display the last rows of the sales DataFrame.
df.tail()

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
1207,10831,1062,Customer_1139,Mumbai,Central,Business,Headphones,Product_021,Mobile App,Debit Card,...,10,4.2,1.0,63,2025-12-09,355710.45,35571.04,320139.41,True,Fast
1208,10751,1241,Customer_1229,Pune,North,Teacher,Printer,Product_051,Partner,Cash,...,0,4.8,8.0,34,2025-07-27,394035.55,0.00,394035.55,True,Normal
1209,10047,1112,Customer_1215,Pune,North,Freelancer,Mobile,Product_012,Store,Credit Card,...,20,2.1,12.0,46,2025-12-05,105552.08,21110.42,84441.66,False,Slow
1210,11133,1199,Customer_1068,Chennai,Central,Professional,Printer,Product_058,Mobile App,Credit Card,...,30,2.9,8.0,41,2025-12-12,20187.00,6056.10,14130.90,False,Normal
1211,10129,1144,Customer_1169,Chennai,West,Student,Monitor,Product_032,Partner,Cash,...,5,2.1,12.0,37,2025-09-06,167883.65,8394.18,159489.47,True,Slow

In [34]:
# Display 10 randomly selected rows from the sales DataFrame.
df.sample(10, random_state=42)

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
801,10802,1076,Customer_1016,Delhi,South,Freelancer,Laptop,Product_058,Mobile App,Credit Card,...,5,3.4,11.0,53,2025-10-06,431115.28,21555.76,409559.52,True,Slow
677,10678,1022,Customer_1225,Mumbai,Central,Teacher,Tablet,Product_040,Online,Credit Card,...,25,3.8,8.0,40,2025-05-12,93378.43,23344.61,70033.82,False,Normal
43,10044,1089,Customer_1123,Madurai,West,Student,Printer,Product_023,Online,Credit Card,...,25,3.4,11.0,23,2025-02-08,196995.42,49248.86,147746.56,True,Slow
990,10991,1086,Customer_1091,Madurai,North,Teacher,Mouse,Product_017,Store,Cash,...,15,2.2,NaN,43,2025-09-09,80381.10,12057.16,68323.94,False,Normal
70,10071,1199,Customer_1093,Mumbai,South,Student,Mobile,Product_025,Mobile App,Net Banking,...,20,1.9,10.0,22,2025-09-01,309818.52,61963.70,247854.82,True,Normal
704,10705,1033,Customer_1084,Pune,North,Business,Camera,Product_051,Online,Cash,...,25,2.2,4.0,34,2025-09-22,229190.82,57297.70,171893.12,True,Fast
908,10909,1093,Customer_1071,Chennai,West,Business,Mobile,Product_053,Mobile App,Debit Card,...,10,2.3,9.0,50,2025-03-10,72302.55,7230.26,65072.29,False,Normal
210,10211,1066,Customer_1016,Delhi,South,Freelancer,Laptop,Product_007,Online,Cash,...,10,4.8,7.0,28,2025-03-24,459579.85,45957.98,413621.87,True,Normal
599,10600,1161,Customer_1131,Hyderabad,South,Freelancer,Laptop,Product_016,Partner,Cash,...,0,3.2,11.0,38,2025-10-24,164504.20,0.00,164504.20,True,Slow
306,10307,1076,Customer_1229,Pune,North,Teacher,Camera,Product_013,Mobile App,Cash,...,15,4.4,13.0,42,2025-11-27,347256.66,52088.50,295168.16,True,Slow

In [36]:
# Display the number of rows and columns in the sales DataFrame.
df.shape

(1212, 23)

In [37]:
# Display the column names of the sales DataFrame.
df.columns

Index(['order_id', 'customer_id', 'customer_name', 'city', 'region',
       'customer_segment', 'product_category', 'product_name', 'sales_channel',
       'payment_method', 'order_status', 'quantity', 'unit_price',
       'discount_pct', 'rating', 'delivery_days', 'customer_age', 'order_date',
       'gross_amount', 'discount_amount', 'net_amount', 'is_high_value',
       'delivery_status'],
      dtype='object')

In [38]:
# Display detailed information about the sales DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1212 non-null   int64
 1   customer_id       1212 non-null   int64
 2   customer_name     1212 non-null   object
 3   city              1212 non-null   object
 4   region            1212 non-null   object
 5   customer_segment  1188 non-null   object
 6   product_category  1212 non-null   object
 7   product_name      1212 non-null   object
 8   sales_channel     1212 non-null   object
 9   payment_method    1194 non-null   object
 10  order_status      1212 non-null   object
 11  quantity          1212 non-null   int64
 12  unit_price        1212 non-null   float64
 13  discount_pct      1212 non-null   int64
 14  rating            1182 non-null   float64
 15  delivery_days     1193 non-null   float64
 16  customer_age      1212 non-null   int64
 17  order_date        1212 non-null   object
 18  gross_amount      1212 non-null   float64
 19  discount_amount   1212 non-null   float64
 20  net_amount        1212 non-null   float64
 21  is_high_value     1212 non-null   bool
 22  delivery_status   1212 non-null   object
dtypes: bool(1), float64(6), int64(5), object(11)
memory usage: 209.6+ KB

In [39]:
# Display descriptive statistics for numeric columns.
df.describe()

,order_id,customer_id,quantity,unit_price,discount_pct,rating,delivery_days,customer_age,gross_amount,discount_amount,net_amount
count,1212.000000,1212.000000,1212.000000,1212.000000,1212.000000,1182.000000,1193.000000,1212.000000,1212.000000,1212.000000,1212.000000
mean,10600.170792,1126.727723,2.968647,61036.981675,14.843234,2.978765,7.629505,41.513201,180479.045536,26872.002979,153607.042558
std,346.852941,71.939098,1.398007,34549.555547,9.953244,1.176238,3.976044,13.862150,140306.869506,30593.815288,121307.499858
min,10001.000000,1002.000000,1.000000,630.500000,0.000000,1.000000,1.000000,18.000000,769.900000,0.000000,646.510000
25%,10299.750000,1064.000000,2.000000,31549.612500,5.000000,1.900000,4.000000,29.000000,71039.662500,4586.985000,58425.442500
50%,10600.500000,1127.500000,3.000000,61586.030000,15.000000,3.000000,8.000000,41.000000,141748.400000,15757.250000,121184.420000
75%,10900.250000,1190.000000,4.000000,90315.020000,25.000000,3.975000,11.000000,54.000000,260352.480000,39483.270000,223632.235000
max,11200.000000,1250.000000,5.000000,119997.250000,30.000000,5.000000,14.000000,65.000000,595177.800000,158840.000000,595177.800000

In [40]:
# Display descriptive statistics for all columns.
df.describe(include="all")

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
count,1212.000000,1212.000000,1212,1212,1212,1188,1212,1212,1212,1194,...,1212.000000,1182.000000,1193.000000,1212.000000,1212,1212.000000,1212.000000,1212.000000,1212,1212
unique,NaN,NaN,246,10,4,5,10,80,4,5,...,NaN,NaN,NaN,NaN,345,NaN,NaN,NaN,2,3
top,NaN,NaN,Customer_1099,Coimbatore,West,Business,Laptop,Product_023,Partner,Credit Card,...,NaN,NaN,NaN,NaN,2025-07-09,NaN,NaN,NaN,True,Normal
freq,NaN,NaN,13,137,326,248,141,23,307,264,...,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,683,456
mean,10600.170792,1126.727723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.843234,2.978765,7.629505,41.513201,NaN,180479.045536,26872.002979,153607.042558,NaN,NaN
std,346.852941,71.939098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.953244,1.176238,3.976044,13.862150,NaN,140306.869506,30593.815288,121307.499858,NaN,NaN
min,10001.000000,1002.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,1.000000,1.000000,18.000000,NaN,769.900000,0.000000,646.510000,NaN,NaN
25%,10299.750000,1064.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,1.900000,4.000000,29.000000,NaN,71039.662500,4586.985000,58425.442500,NaN,NaN
50%,10600.500000,1127.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.000000,3.000000,8.000000,41.000000,NaN,141748.400000,15757.250000,121184.420000,NaN,NaN
75%,10900.250000,1190.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.000000,3.975000,11.000000,54.000000,NaN,260352.480000,39483.270000,223632.235000,NaN,NaN
max,11200.000000,1250.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.000000,5.000000,14.000000,65.000000,NaN,595177.800000,158840.000000,595177.800000,NaN,NaN

In [41]:
# Display the data type of each column.
df.dtypes

order_id              int64
customer_id           int64
customer_name        object
city                 object
region               object
customer_segment     object
product_category     object
product_name         object
sales_channel        object
payment_method       object
order_status         object
quantity              int64
unit_price          float64
discount_pct          int64
rating              float64
delivery_days       float64
customer_age          int64
order_date           object
gross_amount        float64
discount_amount     float64
net_amount          float64
is_high_value          bool
delivery_status      object
dtype: object

In [45]:
# Select the city column and display its first values.
city = df["city"]

print(city.head())

0      Chennai
1    Bengaluru
2         Pune
3    Bengaluru
4       Trichy
Name: city, dtype: object

In [46]:
# Select specific columns and display the first rows.
df[
    [
        "order_id",
        "customer_name",
        "city",
        "product_category",
        "net_amount"
    ]
].head()

   order_id  customer_name       city product_category  net_amount
0     10001  Customer_1220    Chennai       Headphones   115333.85
1     10002  Customer_1120  Bengaluru           Camera    35357.48
2     10003  Customer_1247       Pune       Headphones     4695.68
3     10004  Customer_1191  Bengaluru            Mouse   111979.81
4     10005  Customer_1163     Trichy         Keyboard   291909.80

In [48]:
# Access the city column using attribute notation.
df.city

0         Chennai
1       Bengaluru
2            Pune
3       Bengaluru
4          Trichy
          ...
1207       Mumbai
1208         Pune
1209         Pune
1210      Chennai
1211      Chennai
Name: city, Length: 1212, dtype: object

In [50]:
# Select the first row using its index label.
df.loc[0]

order_id                    10001
customer_id                  1023
customer_name       Customer_1220
city                      Chennai
region                       West
customer_segment          Teacher
product_category       Headphones
product_name          Product_055
sales_channel          Mobile App
payment_method         Debit Card
order_status              Shipped
quantity                        3
unit_price               45228.96
discount_pct                   15
rating                        4.5
delivery_days                11.0
customer_age                   20
order_date             2025-12-16
gross_amount            135686.88
discount_amount          20353.03
net_amount              115333.85
is_high_value                True
delivery_status              Slow
Name: 0, dtype: object

In [51]:
# Select rows 0 through 5 and specific columns using loc.
df.loc[
    0:5,
    [
        "order_id",
        "city",
        "product_category",
        "net_amount"
    ]
]

   order_id       city product_category  net_amount
0     10001    Chennai       Headphones   115333.85
1     10002  Bengaluru           Camera    35357.48
2     10003       Pune       Headphones     4695.68
3     10004  Bengaluru            Mouse   111979.81
4     10005     Trichy         Keyboard   291909.80
5     10006     Mumbai           Tablet    77725.23

In [52]:
# Select the first row using its integer position.
df.iloc[0]

order_id                    10001
customer_id                  1023
customer_name       Customer_1220
city                      Chennai
region                       West
customer_segment          Teacher
product_category       Headphones
product_name          Product_055
sales_channel          Mobile App
payment_method         Debit Card
order_status              Shipped
quantity                        3
unit_price               45228.96
discount_pct                   15
rating                        4.5
delivery_days                11.0
customer_age                   20
order_date             2025-12-16
gross_amount            135686.88
discount_amount          20353.03
net_amount              115333.85
is_high_value                True
delivery_status              Slow
Name: 0, dtype: object

In [53]:
# Select the first five rows and columns using iloc.
df.iloc[0:5, 0:5]

   order_id  customer_id  customer_name       city   region
0     10001         1023  Customer_1220    Chennai     West
1     10002         1194  Customer_1120  Bengaluru    North
2     10003         1164  Customer_1247       Pune    South
3     10004         1110  Customer_1191  Bengaluru    North
4     10005         1109  Customer_1163     Trichy  Central

In [54]:
# Display all unique city values.
df["city"].unique()

array(['Chennai', 'Bengaluru', 'Pune', 'Trichy', 'Mumbai', 'Salem',
       'Delhi', 'Hyderabad', 'Madurai', 'Coimbatore'], dtype=object)

In [55]:
# Count the number of unique cities.
df["city"].nunique()

10

In [56]:
# Count how many records belong to each city.
df["city"].value_counts()

city
Coimbatore    137
Pune          134
Delhi         130
Salem         128
Madurai       124
Trichy        122
Mumbai        118
Bengaluru     110
Chennai       108
Hyderabad     101
Name: count, dtype: int64

In [57]:
# Filter orders where the city is Chennai.
chennai_orders = df[df["city"] == "Chennai"]

chennai_orders.head()

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
9,10010,1024,Customer_1241,Chennai,North,Freelancer,Laptop,Product_075,Mobile App,Cash,...,30,1.1,10.0,44,2025-08-13,299966.04,89989.81,209976.23,True,Normal
11,10012,1244,Customer_1196,Chennai,North,Professional,Printer,Product_001,Partner,Net Banking,...,25,3.7,8.0,46,2025-06-01,94555.44,23638.86,70916.58,False,Normal
39,10040,1158,Customer_1011,Chennai,North,Freelancer,Tablet,Product_078,Mobile App,Debit Card,...,0,1.2,10.0,35,2025-12-10,203312.38,0.00,203312.38,True,Normal
41,10042,1190,Customer_1195,Chennai,Central,Student,Monitor,Product_050,Online,Net Banking,...,5,1.6,12.0,63,2025-09-21,175710.25,8785.51,166924.74,True,Slow

In [59]:
# Filter orders where net_amount is greater than 100000.
df[df["net_amount"] > 100000].head()

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
3,10004,1110,Customer_1191,Bengaluru,North,Teacher,Mouse,Product_011,Partner,Credit Card,...,5,1.1,11.0,29,2025-07-29,117873.48,5893.67,111979.81,True,Slow
4,10005,1109,Customer_1163,Trichy,Central,Teacher,Keyboard,Product_001,Partner,Debit Card,...,20,1.0,4.0,21,2025-10-04,364887.25,72977.45,291909.80,True,Fast
6,10007,1022,Customer_1129,Trichy,West,Business,Tablet,Product_079,Online,Credit Card,...,15,1.5,8.0,25,2025-04-20,130960.74,19644.11,111316.63,True,Normal
9,10010,1024,Customer_1241,Chennai,North,Freelancer,Laptop,Product_075,Mobile App,Cash,...,30,1.1,10.0,44,2025-08-13,299966.04,89989.81,209976.23,True,Normal

In [61]:
# Filter Chennai customers whose net_amount is greater than 50000.
#Find the customers from Chennai whose net_amount is greater than 50,000.

df[
    (df["city"] == "Chennai") &
    (df["net_amount"] > 50000)
].head()

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
9,10010,1024,Customer_1241,Chennai,North,Freelancer,Laptop,Product_075,Mobile App,Cash,...,30,1.1,10.0,44,2025-08-13,299966.04,89989.81,209976.23,True,Normal
11,10012,1244,Customer_1196,Chennai,North,Professional,Printer,Product_001,Partner,Net Banking,...,25,3.7,8.0,46,2025-06-01,94555.44,23638.86,70916.58,False,Normal
39,10040,1158,Customer_1011,Chennai,North,Freelancer,Tablet,Product_078,Mobile App,Debit Card,...,0,1.2,10.0,35,2025-12-10,203312.38,0.00,203312.38,True,Normal
41,10042,1190,Customer_1195,Chennai,Central,Student,Monitor,Product_050,Online,Net Banking,...,5,1.6,12.0,63,2025-09-21,175710.25,8785.51,166924.74,True,Slow

In [62]:
# Filter the first five customers from Chennai or Madurai.
#Find the first 5 customers who belong to either Chennai or Madurai.

df[
    (df["city"] == "Chennai") |
    (df["city"] == "Madurai")
].head()

,order_id,customer_id,customer_name,city,region,customer_segment,product_category,product_name,sales_channel,payment_method,...,discount_pct,rating,delivery_days,customer_age,order_date,gross_amount,discount_amount,net_amount,is_high_value,delivery_status
0,10001,1023,Customer_1220,Chennai,West,Teacher,Headphones,Product_055,Mobile App,Debit Card,...,15,4.5,11.0,20,2025-12-16,135686.88,20353.03,115333.85,True,Slow
9,10010,1024,Customer_1241,Chennai,North,Freelancer,Laptop,Product_075,Mobile App,Cash,...,30,1.1,10.0,44,2025-08-13,299966.04,89989.81,209976.23,True,Normal
11,10012,1244,Customer_1196,Chennai,North,Professional,Printer,Product_001,Partner,Net Banking,...,25,3.7,8.0,46,2025-06-01,94555.44,23638.86,70916.58,False,Normal
17,10018,1033,Customer_1184,Madurai,West,Professional,Laptop,Product_016,Store,Debit Card,...,30,2.6,4.0,28,2025-07-07,86013.09,25803.93,60209.16,False,Fast
18,10019,1210,Customer_1203,Madurai,West,Business,Printer,Product_021,Mobile App,Debit Card,...,20,3.8,1.0,48,2025-01-28,66764.08,13352.82,53411.26,False,Fast