---
# *Task 1: Employee Performance Analysis*
---

In [6]:
import pandas as pd

employee_scores = pd.Series(
    [85, 72, 91, 68, 95, 78],
    index=["EMP101", "EMP102", "EMP103", "EMP104", "EMP105", "EMP106"]
)

employee_scores

EMP101    85
EMP102    72
EMP103    91
EMP104    68
EMP105    95
EMP106    78
dtype: int64

---
# *Task 2: Hospital Patient Records*
---

In [25]:
# 1. Create the DataFrame.

patient_data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105", "P106"],
    "Name": ["Arun", "Meena", "Ravi", "Divya", "Kumar", "Priya"],
    "Age": [32, 28, 45, 36, 52, 41],
    "Department": [
        "Cardiology", "Neurology", "Orthopedic",
        "Cardiology", "General", "Neurology"
    ],
    "Bill_Amount": [4500, 6200, 3800, 5100, 2900, 7200]
}

patient_df = pd.DataFrame(patient_data)

patient_df

  Patient_ID   Name  Age  Department  Bill_Amount
0       P101   Arun   32  Cardiology         4500
1       P102  Meena   28   Neurology         6200
2       P103   Ravi   45  Orthopedic         3800
3       P104  Divya   36  Cardiology         5100
4       P105  Kumar   52     General         2900
5       P106  Priya   41   Neurology         7200

In [8]:
# 2. Display the first few patient records.

patient_df.head()

  Patient_ID   Name  Age  Department  Bill_Amount
0       P101   Arun   32  Cardiology         4500
1       P102  Meena   28   Neurology         6200
2       P103   Ravi   45  Orthopedic         3800
3       P104  Divya   36  Cardiology         5100
4       P105  Kumar   52     General         2900

In [9]:
# 3. Display the last few patient records.

patient_df.tail()

  Patient_ID   Name  Age  Department  Bill_Amount
1       P102  Meena   28   Neurology         6200
2       P103   Ravi   45  Orthopedic         3800
3       P104  Divya   36  Cardiology         5100
4       P105  Kumar   52     General         2900
5       P106  Priya   41   Neurology         7200

In [11]:
# 4. Find the number of rows and columns.

patient_df.shape

(6, 5)

In [12]:
# 5. Display all column names.

patient_df.columns

Index(['Patient_ID', 'Name', 'Age', 'Department', 'Bill_Amount'], dtype='str')

In [15]:
# 6. Display the row labels.

print(patient_df.index)

RangeIndex(start=0, stop=6, step=1)

In [24]:
# 7. Identify the data type of every column.

patient_df.dtypes

Patient_ID       str
Name             str
Age            int64
Department       str
Bill_Amount    int64
dtype: object

In [28]:
# 8. Get a complete summary of the DataFrame, including the number of entries, columns, non-null values, and data types.

patient_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Patient_ID   6 non-null      str
 1   Name         6 non-null      str
 2   Age          6 non-null      int64
 3   Department   6 non-null      str
 4   Bill_Amount  6 non-null      int64
dtypes: int64(2), str(3)
memory usage: 479.0 bytes