In [1]:
import pandas as pd

df = pd.read_csv(r"C:/Users/Asus/Downloads/Healthcare.csv")
df

,Patient_ID,Patient Name,Gender,Appointment Date,Age,City,Department,Doctor Name,Appointment Type,Appointment Status,Insurance Type,Booking Channel,Wait Time Minutes,Consultation Duration,Follow Up Required,Symptoms
0,P100100,Anitha Krishnan,Male,09:47.9,80,Trichy,ENT,Dr. Divya,Emergency,Completed,Corporate,Mobile App,34,53.0,No,Routine Review
1,P101216,Meena Reddy,Female,49:32.6,61,Bangalore,Neurology,Dr. Priya,Follow-up,Completed,Corporate,Mobile App,105,73.0,No,Joint Pain
2,P104711,Lakshmi Iyer,Male,04:59.1,22,Salem,Orthopedics,NaN,Emergency,No Show,Private,Phone,44,74.0,Yes,Skin Rash
3,P101991,Keerthi Das,Male,50:28.7,57,Pune,Dental,Dr. Suresh,New Patient,Cancelled,Private,Walk-in,73,65.0,Yes,Back Pain
4,P103301,Lakshmi Reddy,Female,52:50.0,17,Coimbatore,Orthopedics,Dr. Nisha,Emergency,No Show,Corporate,Phone,114,50.0,No,Back Pain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,P105188,Lakshmi Rao,Female,35:31.3,26,Salem,Dermatology,Dr. Arun,Emergency,Completed,Self Pay,Hospital Desk,83,23.0,No,Ear Pain
5231,P101768,Arun Sharma,Male,12:25.8,21,Bengaluru,Ophthalmology,Dr. Priya,Teleconsultation,Scheduled,Corporate,Walk-in,57,66.0,No,Eye Irritation
5232,P101737,Divya Iyer,Female,57:59.5,66,Madurai,Pediatrics,Dr. Arun,Follow-up,Completed,Self Pay,Website,74,14.0,No,Eye Irritation
5233,P103240,Keerthi Rao,Female,53:27.4,61,Mysuru,Ophthalmology,Dr. Rajesh,Follow-up,Completed,Self Pay,Phone,12,89.0,No,Skin Rash
5234,P104737,Meena Kumar,Female,51:56.0,23,Trichy,Neurology,Dr. Meena,New Patient,Scheduled,Government,Hospital Desk,108,58.0,No,Headache

In [2]:
# Data errors:
# 1. Missing Values - Empty Cell / Blank Value
# 2. Duplicate rows
# 3. Incorrect/inconsistent dawta
# 4. Extra spaces / Unwanted Spaces - Strings
# 5. Wrong Data Types
# 6. Invalid Data - Phone numbers - 10 num, -ve sign
# 7. Renaming Columns

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5235 entries, 0 to 5234
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             5235 non-null   str
 1   Patient Name           5235 non-null   str
 2   Gender                 5160 non-null   str
 3   Appointment Date       5235 non-null   str
 4   Age                    5235 non-null   int64
 5   City                   5133 non-null   str
 6   Department             5235 non-null   str
 7   Doctor Name            5051 non-null   str
 8   Appointment Type       5235 non-null   str
 9   Appointment Status     5235 non-null   str
 10  Insurance Type         4818 non-null   str
 11  Booking Channel        5104 non-null   str
 12  Wait Time Minutes      5028 non-null   str
 13  Consultation Duration  5051 non-null   float64
 14  Follow Up Required     5130 non-null   str
 15  Symptoms               5078 non-null   str
dtypes: float64(1), int64(1), str(14)
memory usage: 1.2 MB

In [4]:
df.head(20)

,Patient_ID,Patient Name,Gender,Appointment Date,Age,City,Department,Doctor Name,Appointment Type,Appointment Status,Insurance Type,Booking Channel,Wait Time Minutes,Consultation Duration,Follow Up Required,Symptoms
0,P100100,Anitha Krishnan,Male,09:47.9,80,Trichy,ENT,Dr. Divya,Emergency,Completed,Corporate,Mobile App,34,53.0,No,Routine Review
1,P101216,Meena Reddy,Female,49:32.6,61,Bangalore,Neurology,Dr. Priya,Follow-up,Completed,Corporate,Mobile App,105,73.0,No,Joint Pain
2,P104711,Lakshmi Iyer,Male,04:59.1,22,Salem,Orthopedics,NaN,Emergency,No Show,Private,Phone,44,74.0,Yes,Skin Rash
3,P101991,Keerthi Das,Male,50:28.7,57,Pune,Dental,Dr. Suresh,New Patient,Cancelled,Private,Walk-in,73,65.0,Yes,Back Pain
4,P103301,Lakshmi Reddy,Female,52:50.0,17,Coimbatore,Orthopedics,Dr. Nisha,Emergency,No Show,Corporate,Phone,114,50.0,No,Back Pain
5,P101903,Karthik Sharma,Male,34:39.4,36,Madurai,General Medicine,Dr. Anil,Emergency,Completed,Government,Phone,53,43.0,No,Abdominal Pain
6,P101171,Naveen Menon,Male,42:08.1,35,Coimbatore,Ophthalmology,Dr. Kumar,Emergency,Scheduled,Private,Hospital Desk,49,27.0,Yes,Joint Pain
7,P102338,Swetha Patel,Female,26:16.7,78,Coimbatore,General Medicine,Dr. Priya,Routine Checkup,Scheduled,Government,Mobile App,94,NaN,No,Ear Pain
8,P101065,Ravi Krishnan,Female,35:20.9,39,Kochi,Orthopedics,Dr. Rajesh,New Patient,Completed,Private,Hospital Desk,14,68.0,No,Ear Pain
9,P103898,Deepa Sharma,Female,23:07.7,65,Mysuru,Gynecology,Dr. Priya,Routine Checkup,Cancelled,Government,Hospital Desk,76,90.0,Yes,Headache
10,P105093,Lakshmi Reddy,Male,53:12.8,49,Coimbatore,Ophthalmology,NaN,Teleconsultation,No Show,Private,Website,68,31.0,Yes,Headache
11,P100077,Vikram Das,Female,51:20.7,56,Pune,Orthopedics,Dr. Priya,Routine Checkup,Completed,Self Pay,NaN,90,84.0,No,Headache
12,P102824,Harini Krishnan,Male,22:17.8,57,Bengaluru,Orthopedics,Dr. Kavitha,Follow-up,Completed,Government,Hospital Desk,86,81.0,No,Skin Rash
13,P104946,Arun Patel,Male,37:00.7,44,Coimbatore,Dental,Dr. Rajesh,New Patient,Completed,Corporate,Phone,39,89.0,No,Back Pain
14,P103398,Priya Das,Female,34:08.2,50,Kochi,Ophthalmology,Dr. Arun,Emergency,Scheduled,Self Pay,Mobile App,53,47.0,No,Fever
15,P103641,Ravi Kumar,Male,02:08.8,17,Pune,ENT,Dr. Rajesh,Emergency,Completed,Private,Walk-in,24,68.0,No,Ear Pain
16,P104447,Lakshmi Nair,Male,17:31.1,52,Hyderabad,Neurology,Dr. Divya,Teleconsultation,Scheduled,Government,Mobile App,120,57.0,No,Skin Rash
17,P102479,Sanjay Krishnan,Male,45:29.6,46,Coimbatore,Orthopedics,Dr. Priya,Routine Checkup,Completed,Private,Website,10,88.0,Yes,Ear Pain
18,P101311,Karthik Krishnan,Male,31:51.1,29,Hyderabad,Neurology,Dr. Suresh,New Patient,Completed,Private,Walk-in,14,69.0,No,Ear Pain
19,P103037,Sanjay Kumar,Male,05:22.0,43,Coimbatore,Dental,Dr. Anil,Emergency,Completed,Self Pay,Mobile App,95,89.0,Yes,Cough

In [5]:
# Creating raw data - backup

raw_df = df.copy()
print("Raw Data Created")

Raw Data Created

In [6]:
# Creating clean df

clean_df = df.copy()
print("Clean Data Created")

Clean Data Created

In [7]:
# Missing Values
# True -> Value is Missing False -> Value is present

clean_df.isnull()

,Patient_ID,Patient Name,Gender,Appointment Date,Age,City,Department,Doctor Name,Appointment Type,Appointment Status,Insurance Type,Booking Channel,Wait Time Minutes,Consultation Duration,Follow Up Required,Symptoms
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5230,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5231,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5232,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5233,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5234,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
# Count the missing values column level

clean_df.isnull().sum()

Patient_ID                 0
Patient Name               0
Gender                    75
Appointment Date           0
Age                        0
City                     102
Department                 0
Doctor Name              184
Appointment Type           0
Appointment Status         0
Insurance Type           417
Booking Channel          131
Wait Time Minutes        207
Consultation Duration    184
Follow Up Required       105
Symptoms                 157
dtype: int64

In [9]:
# Count the missing values row level

clean_df.isnull().any(axis=1)

0       False
1       False
2        True
3       False
4       False
        ...
5230    False
5231    False
5232    False
5233    False
5234    False
Length: 5235, dtype: bool

In [10]:
clean_df.isnull().any(axis=1).sum()

np.int64(1385)

In [11]:
clean_df["Gender"].isnull().sum()

np.int64(75)

In [12]:
# Identify missing value in a specific column

missing_genders = clean_df[
    clean_df["Gender"].isnull()
]
missing_genders.head(20)

,Patient_ID,Patient Name,Gender,Appointment Date,Age,City,Department,Doctor Name,Appointment Type,Appointment Status,Insurance Type,Booking Channel,Wait Time Minutes,Consultation Duration,Follow Up Required,Symptoms
116,P102995,Arun Nair,NaN,26:27.1,78,Trichy,ENT,Dr. Rajesh,Routine Checkup,Rescheduled,Self Pay,Phone,113,30.0,No,Joint Pain
152,P101586,Vikram Reddy,NaN,43:47.8,54,Bengaluru,Dental,Dr. Nisha,Emergency,Completed,Government,Website,46,35.0,No,Back Pain
159,P100846,Keerthi Reddy,NaN,55:17.5,75,Chennai,Ophthalmology,Dr. Kavitha,New Patient,Completed,Corporate,Mobile App,17,57.0,No,Routine Review
173,P102101,Suresh Sharma,NaN,55:15.4,28,Trichy,Neurology,Dr. Kavitha,New Patient,No Show,Self Pay,Website,50,77.0,Yes,Skin Rash
176,P102465,Arun Menon,NaN,52:31.3,79,Pune,Dental,NaN,Routine Checkup,Completed,Private,NaN,51,28.0,No,Routine Review
180,P102484,Arun Rao,NaN,12:59.0,43,Madurai,Dermatology,Dr. Divya,Routine Checkup,Completed,Government,Walk-in,87,17.0,Yes,Abdominal Pain
381,P102167,Sanjay Nair,NaN,22:07.4,80,Coimbatore,Cardiology,Dr. Kumar,Follow-up,Completed,Government,Phone,7,66.0,No,Routine Review
414,P103262,Divya Kumar,NaN,42:24.7,46,Trichy,Dermatology,Dr. Nisha,Teleconsultation,Scheduled,Government,Website,87.0 min,NaN,Yes,Eye Irritation
536,P101852,Sanjay Patel,NaN,30:15.6,51,Mysuru,Pediatrics,Dr. Kumar,Follow-up,Completed,Self Pay,Walk-in,106,17.0,No,Ear Pain
668,P101919,Harini Krishnan,NaN,26:37.5,21,Bengaluru,Ophthalmology,Dr. Nisha,New Patient,Completed,Government,Mobile App,NaN,NaN,No,Headache
716,P100057,Naveen Patel,NaN,01:23.1,73,Madurai,General Medicine,Dr. Kumar,New Patient,Completed,Private,Website,NaN,44.0,No,Fever
815,P104270,Naveen Krishnan,NaN,16:22.6,21,Bengaluru,Dental,Dr. Suresh,Teleconsultation,Completed,Private,Mobile App,18,NaN,Yes,Joint Pain
871,P103483,Sanjay Patel,NaN,21:27.9,52,Coimbatore,Pediatrics,Dr. Kavitha,Teleconsultation,Scheduled,NaN,Website,115,61.0,Yes,Ear Pain
1107,P103159,Lakshmi Reddy,NaN,04:07.2,36,Mysuru,Gynecology,Dr. Kumar,Teleconsultation,Completed,Government,Mobile App,24,81.0,No,Headache
1221,P104432,Ajay Rao,NaN,55:02.9,55,Mysuru,ENT,NaN,Routine Checkup,Scheduled,Private,Hospital Desk,119,18.0,No,Eye Irritation
1256,P102774,Rahul Menon,NaN,47:23.9,84,Bengaluru,Cardiology,Dr. Anil,New Patient,Completed,Government,Walk-in,95,61.0,Yes,Eye Irritation
1285,P104464,Keerthi Sharma,NaN,38:59.1,35,Kochi,Dermatology,Dr. Suresh,New Patient,No Show,Corporate,Phone,107,73.0,No,Headache
1378,P102322,Arun Nair,NaN,34:18.6,77,Hyderabad,Dermatology,Dr. Kumar,New Patient,Scheduled,Private,Website,NaN,76.0,NaN,Ear Pain
1458,P100908,Rahul Iyer,NaN,24:10.0,61,Coimbatore,ENT,Dr. Nisha,Emergency,Completed,Government,Hospital Desk,13,51.0,Yes,Skin Rash
1535,P102474,Divya Reddy,NaN,18:00.2,26,Salem,Orthopedics,Dr. Kumar,Follow-up,Completed,Private,Walk-in,43,40.0,Yes,Skin Rash

In [13]:
# Handle Missing Values
# Method 1: dropna() - Remove rows - Not Mostly Applicable
# Method 2: fillna() - Fill with Constant values (Fixed Value)
# Method 3: Fill Numerical values with mean
# Method 4: Fill Numberical values with median
# Method 5: Outliers

In [14]:
# Method 2: fillna() - Fill with Constant values (Fixed Value)

clean_df["Gender"] = clean_df["Gender"].fillna("Unknown")

In [15]:
clean_df.isnull().sum()

Patient_ID                 0
Patient Name               0
Gender                     0
Appointment Date           0
Age                        0
City                     102
Department                 0
Doctor Name              184
Appointment Type           0
Appointment Status         0
Insurance Type           417
Booking Channel          131
Wait Time Minutes        207
Consultation Duration    184
Follow Up Required       105
Symptoms                 157
dtype: int64

In [16]:
missing_genders = clean_df[
    clean_df["Gender"].isnull()
]
missing_genders.head(20)

Empty DataFrame
Columns: [Patient_ID, Patient Name, Gender, Appointment Date, Age, City, Department, Doctor Name, Appointment Type, Appointment Status, Insurance Type, Booking Channel, Wait Time Minutes, Consultation Duration, Follow Up Required, Symptoms]
Index: []

In [17]:
clean_df["City"] = clean_df["City"].fillna("Unknown")
clean_df["Doctor Name"] = clean_df["Doctor Name"].fillna("Not Assigned")
clean_df["Insurance Type"] = clean_df["Insurance Type"].fillna("Unknown")
clean_df["Booking Channel"] = clean_df["Booking Channel"].fillna("Not Available")
clean_df["Follow Up Required"] = clean_df["Follow Up Required"].fillna("Unknown")
clean_df["Symptoms"] = clean_df["Symptoms"].fillna("Not Found")

In [18]:
clean_df.isnull().sum()

Patient_ID                 0
Patient Name               0
Gender                     0
Appointment Date           0
Age                        0
City                       0
Department                 0
Doctor Name                0
Appointment Type           0
Appointment Status         0
Insurance Type             0
Booking Channel            0
Wait Time Minutes        207
Consultation Duration    184
Follow Up Required         0
Symptoms                   0
dtype: int64

In [19]:
# Convert the column to numerical

clean_df["Wait Time Minutes"] = pd.to_numeric(
    clean_df["Wait Time Minutes"],
    errors = "coerce"
)

clean_df["Wait Time Minutes"].dtype

dtype('float64')

In [20]:
# Method 3: Fill Numerical values with mean

wait_time_mean = clean_df["Wait Time Minutes"].mean()
wait_time_mean

np.float64(61.7865213882163)

In [21]:
# Method: Handling Missing Values using Forward Fill and Backward Fill
data = pd.DataFrame({
    "Employee":["Arun", "Priya", "Rahul", "Divya", "Venkat", "Karthik"],
    "Dept": ["IT", None, "HR", None, "Sales", "HR"],
    "Salary": [20000, 21000, None, 45000, None, None]
})

data

  Employee   Dept   Salary
0     Arun     IT  20000.0
1    Priya    NaN  21000.0
2    Rahul     HR      NaN
3    Divya    NaN  45000.0
4   Venkat  Sales      NaN
5  Karthik     HR      NaN

In [22]:
data.isnull().sum()

Employee    0
Dept        2
Salary      3
dtype: int64

In [23]:
# Forward Fill - ffill()

data["Dept"] = data["Dept"].ffill()
data

  Employee   Dept   Salary
0     Arun     IT  20000.0
1    Priya     IT  21000.0
2    Rahul     HR      NaN
3    Divya     HR  45000.0
4   Venkat  Sales      NaN
5  Karthik     HR      NaN

In [24]:
# Backward Fill - bfill()

data["Salary"] = data["Salary"].bfill()
data

  Employee   Dept   Salary
0     Arun     IT  20000.0
1    Priya     IT  21000.0
2    Rahul     HR  45000.0
3    Divya     HR  45000.0
4   Venkat  Sales      NaN
5  Karthik     HR      NaN

In [25]:
data["Salary"] = data["Salary"].ffill()
data

  Employee   Dept   Salary
0     Arun     IT  20000.0
1    Priya     IT  21000.0
2    Rahul     HR  45000.0
3    Divya     HR  45000.0
4   Venkat  Sales  45000.0
5  Karthik     HR  45000.0

In [26]:
data.isnull().sum()

Employee    0
Dept        0
Salary      0
dtype: int64

In [27]:
clean_df["Wait Time Minutes"] = clean_df["Wait Time Minutes"].fillna(wait_time_mean)

clean_df.isnull().sum()

Patient_ID                 0
Patient Name               0
Gender                     0
Appointment Date           0
Age                        0
City                       0
Department                 0
Doctor Name                0
Appointment Type           0
Appointment Status         0
Insurance Type             0
Booking Channel            0
Wait Time Minutes          0
Consultation Duration    184
Follow Up Required         0
Symptoms                   0
dtype: int64

In [28]:
# Handling duplicates - Repeated Rows - duplicated()

clean_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5230    False
5231    False
5232    False
5233    False
5234    False
Length: 5235, dtype: bool

In [29]:
clean_df.duplicated().sum() # Excluding Unique

np.int64(35)

In [30]:
clean_df.duplicated(keep = False).sum() # Including Unique

np.int64(70)

In [31]:
clean_df = clean_df.drop_duplicates()

In [32]:
clean_df.duplicated().sum()

np.int64(0)

In [34]:
clean_df.info()

<class 'pandas.DataFrame'>
Index: 5200 entries, 0 to 5234
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Patient_ID             5200 non-null   str
 1   Patient Name           5200 non-null   str
 2   Gender                 5200 non-null   str
 3   Appointment Date       5200 non-null   str
 4   Age                    5200 non-null   int64
 5   City                   5200 non-null   str
 6   Department             5200 non-null   str
 7   Doctor Name            5200 non-null   str
 8   Appointment Type       5200 non-null   str
 9   Appointment Status     5200 non-null   str
 10  Insurance Type         5200 non-null   str
 11  Booking Channel        5200 non-null   str
 12  Wait Time Minutes      5200 non-null   float64
 13  Consultation Duration  5018 non-null   float64
 14  Follow Up Required     5200 non-null   str
 15  Symptoms               5200 non-null   str
dtypes: float64(2), int64(1), str(13)
memory usage: 1.2 MB

In [36]:
text_columns = clean_df.select_dtypes(include = "str").columns
text_columns

Index(['Patient_ID', 'Patient Name', 'Gender', 'Appointment Date', 'City',
       'Department', 'Doctor Name', 'Appointment Type', 'Appointment Status',
       'Insurance Type', 'Booking Channel', 'Follow Up Required', 'Symptoms'],
      dtype='str')