In [168]:
# Importing pandas lib and loding csv
import pandas as pd

raw_data = pd.read_csv(r"university_event_registration_lab 8.csv")

raw_data.head()

,Student ID,Student Name,Gender,Event Date,Age,City,Department,Event Type,Registration Date,Registration Channel,Payment Status,Attendance Status,Meal Preference,Registration Fee,Event Duration Hours,Feedback Rating
0,S12237,Lakshmi Rao,Other,8/2/2026,19,Kochi,Computer Science,Sports Meet,8/1/2026,Email,paid,Cancelled,Vegetarian,150,1,3
1,S11565,Manoj Kumar,Male,3/2/2026,21,Trichy,Mechanical,Career Fair,9/2/2026,Email,Waived,Cancelled,Non-Vegetarian,200,2,4
2,S12093,Swetha Menon,Other,5/15/2026,21,Salem,Arts,Workshop,16/04/2026,Website,Refunded,absent,Vegan,Rs 750,2.5 hours,5
3,S11090,Manoj Kumar,NaN,3/25/2026,18,Chennai,Arts,Cultural Fest,16/03/2026,Mobile App,Waived,absent,Non-Vegetarian,Rs 200,3.0 hours,3
4,S11896,Priya Sharma,female,20-Jan-26,24,Hyderabad,NaN,Hackathon,11/1/2026,Campus Desk,Waived,Cancelled,Non-Vegetarian,200,4,2

In [169]:
# Copying

raw_df = raw_data.copy()
clean_df = raw_df.copy()

In [170]:
clean_df.columns

Index(['Student ID', 'Student Name', 'Gender', 'Event Date', 'Age', 'City',
       'Department', 'Event Type', 'Registration Date', 'Registration Channel',
       'Payment Status', 'Attendance Status', 'Meal Preference',
       'Registration Fee', 'Event Duration Hours', 'Feedback Rating'],
      dtype='str')

In [171]:
# renaming columns

clean_df = clean_df.rename(columns = {
    'Student ID' :'student_id', 
    'Student Name':'student_name', 
    'Gender': 'gender',
    'Event Date' : 'event_date', 
    'Age': 'age', 
    'City': 'city',
    'Department': 'department', 
    'Event Type': 'event_type', 
    'Registration Date': 'registration_date', 
    'Registration Channel':'registration_channel',
    'Payment Status': 'payment_status', 
    'Attendance Status':'attendance_status', 
    'Meal Preference':'meal_preference',
    'Registration Fee':'registration_fee', 
    'Event Duration Hours':'event_duration_hours', 
    'Feedback Rating':'feedback_rating'
})
print(clean_df.columns)

Index(['student_id', 'student_name', 'gender', 'event_date', 'age', 'city',
       'department', 'event_type', 'registration_date', 'registration_channel',
       'payment_status', 'attendance_status', 'meal_preference',
       'registration_fee', 'event_duration_hours', 'feedback_rating'],
      dtype='str')

In [172]:
# Finding Null Values column wise

clean_df.isnull().sum()

student_id                0
student_name              0
gender                   75
event_date               16
age                       0
city                    103
department               58
event_type                0
registration_date        10
registration_channel     88
payment_status            0
attendance_status         0
meal_preference          71
registration_fee          0
event_duration_hours      0
feedback_rating         146
dtype: int64

In [173]:
# Finding null values row wise

clean_df.isnull().any(axis=1).sum()

np.int64(521)

In [174]:
clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            3000 non-null   str
 1   student_name          3000 non-null   str
 2   gender                2925 non-null   str
 3   event_date            2984 non-null   str
 4   age                   3000 non-null   int64
 5   city                  2897 non-null   str
 6   department            2942 non-null   str
 7   event_type            3000 non-null   str
 8   registration_date     2990 non-null   str
 9   registration_channel  2912 non-null   str
 10  payment_status        3000 non-null   str
 11  attendance_status     3000 non-null   str
 12  meal_preference       2929 non-null   str
 13  registration_fee      3000 non-null   str
 14  event_duration_hours  3000 non-null   str
 15  feedback_rating       2854 non-null   str
dtypes: int64(1), str(15)
memory usage: 690.6 KB

In [175]:
# Filling Null Values

clean_df['gender'] = clean_df['gender'].fillna("Unknown")
clean_df['city'] = clean_df['city'].fillna("Unknown")
clean_df["department"] = clean_df["department"].fillna("Unknown")
clean_df["registration_channel"] = clean_df["registration_channel"].fillna("Unknown")
clean_df["meal_preference"] = clean_df["meal_preference"].fillna("Unknown")

clean_df.isnull().sum()

student_id                0
student_name              0
gender                    0
event_date               16
age                       0
city                      0
department                0
event_type                0
registration_date        10
registration_channel      0
payment_status            0
attendance_status         0
meal_preference           0
registration_fee          0
event_duration_hours      0
feedback_rating         146
dtype: int64

In [176]:
# Converting String to numeric dtype

clean_df['feedback_rating'] = pd.to_numeric(clean_df['feedback_rating'], errors = 'coerce')
clean_df['event_date'] = pd.to_datetime(clean_df['event_date'], format = 'mixed', errors = 'coerce')
clean_df["registration_date"] = pd.to_datetime(clean_df["registration_date"],format = 'mixed', errors = 'coerce')
clean_df['event_duration_hours'] = pd.to_numeric(clean_df['event_duration_hours'],errors ='coerce')
clean_df['registration_fee'] = pd.to_numeric(clean_df['registration_fee'],errors ='coerce')

clean_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            3000 non-null   str
 1   student_name          3000 non-null   str
 2   gender                3000 non-null   str
 3   event_date            2964 non-null   datetime64[us]
 4   age                   3000 non-null   int64
 5   city                  3000 non-null   str
 6   department            3000 non-null   str
 7   event_type            3000 non-null   str
 8   registration_date     2975 non-null   datetime64[us]
 9   registration_channel  3000 non-null   str
 10  payment_status        3000 non-null   str
 11  attendance_status     3000 non-null   str
 12  meal_preference       3000 non-null   str
 13  registration_fee      2385 non-null   float64
 14  event_duration_hours  2395 non-null   float64
 15  feedback_rating       2287 non-null   float64
dtypes: datetime64[us](2), float64(3), int64(1), str(10)
memory usage: 612.2 KB

In [177]:
clean_df.head()

,student_id,student_name,gender,event_date,age,city,department,event_type,registration_date,registration_channel,payment_status,attendance_status,meal_preference,registration_fee,event_duration_hours,feedback_rating
0,S12237,Lakshmi Rao,Other,2026-08-02,19,Kochi,Computer Science,Sports Meet,2026-08-01,Email,paid,Cancelled,Vegetarian,150.0,1.0,3.0
1,S11565,Manoj Kumar,Male,2026-03-02,21,Trichy,Mechanical,Career Fair,2026-09-02,Email,Waived,Cancelled,Non-Vegetarian,200.0,2.0,4.0
2,S12093,Swetha Menon,Other,2026-05-15,21,Salem,Arts,Workshop,2026-04-16,Website,Refunded,absent,Vegan,NaN,NaN,5.0
3,S11090,Manoj Kumar,Unknown,2026-03-25,18,Chennai,Arts,Cultural Fest,2026-03-16,Mobile App,Waived,absent,Non-Vegetarian,NaN,NaN,3.0
4,S11896,Priya Sharma,female,2026-01-20,24,Hyderabad,Unknown,Hackathon,2026-11-01,Campus Desk,Waived,Cancelled,Non-Vegetarian,200.0,4.0,2.0

In [178]:
print(clean_df.isna().sum())

student_id                0
student_name              0
gender                    0
event_date               36
age                       0
city                      0
department                0
event_type                0
registration_date        25
registration_channel      0
payment_status            0
attendance_status         0
meal_preference           0
registration_fee        615
event_duration_hours    605
feedback_rating         713
dtype: int64

In [179]:
# Remove Extra Spaces

for columns in clean_df.select_dtypes(include='str'):
    clean_df[columns] = clean_df[columns].str.lower().str.strip()

clean_df.head()

,student_id,student_name,gender,event_date,age,city,department,event_type,registration_date,registration_channel,payment_status,attendance_status,meal_preference,registration_fee,event_duration_hours,feedback_rating
0,s12237,lakshmi rao,other,2026-08-02,19,kochi,computer science,sports meet,2026-08-01,email,paid,cancelled,vegetarian,150.0,1.0,3.0
1,s11565,manoj kumar,male,2026-03-02,21,trichy,mechanical,career fair,2026-09-02,email,waived,cancelled,non-vegetarian,200.0,2.0,4.0
2,s12093,swetha menon,other,2026-05-15,21,salem,arts,workshop,2026-04-16,website,refunded,absent,vegan,NaN,NaN,5.0
3,s11090,manoj kumar,unknown,2026-03-25,18,chennai,arts,cultural fest,2026-03-16,mobile app,waived,absent,non-vegetarian,NaN,NaN,3.0
4,s11896,priya sharma,female,2026-01-20,24,hyderabad,unknown,hackathon,2026-11-01,campus desk,waived,cancelled,non-vegetarian,200.0,4.0,2.0

In [180]:
clean_df['event_duration_hours'].dtypes

dtype('float64')

In [181]:
# Filling date columns

clean_df["event_date"] = clean_df["event_date"].fillna(pd.Timestamp("1900-01-01"))
clean_df["registration_date"] = clean_df["registration_date"].fillna(pd.Timestamp("1900-01-01"))
clean_df.isnull().sum()

student_id                0
student_name              0
gender                    0
event_date                0
age                       0
city                      0
department                0
event_type                0
registration_date         0
registration_channel      0
payment_status            0
attendance_status         0
meal_preference           0
registration_fee        615
event_duration_hours    605
feedback_rating         713
dtype: int64

In [182]:
# Filling missing values using mean and median

event_duration_hrs_median = clean_df['event_duration_hours'].median()
clean_df['event_duration_hours'] = clean_df['event_duration_hours'].fillna(event_duration_hrs_median)

feedback_rating_mean = clean_df['feedback_rating'].mean()
clean_df['feedback_rating'] = clean_df['feedback_rating'].fillna(feedback_rating_mean.round())

clean_df.isnull().sum()

student_id                0
student_name              0
gender                    0
event_date                0
age                       0
city                      0
department                0
event_type                0
registration_date         0
registration_channel      0
payment_status            0
attendance_status         0
meal_preference           0
registration_fee        615
event_duration_hours      0
feedback_rating           0
dtype: int64

In [183]:
# Checking Unique Values

print("Gender \n", clean_df["gender"].unique())
print("Age \n", clean_df["age"].unique())
print("Cities \n", clean_df["city"].unique())
print("Department \n", clean_df["department"].unique())
print("Event Type \n", clean_df["event_type"].unique())
print("Reg Channel \n", clean_df["registration_channel"].unique())
print("Payment Status \n", clean_df["payment_status"].unique())
print("Attendance Status \n", clean_df["attendance_status"].unique())
print("Meal Pref \n", clean_df["meal_preference"].unique())
print("Registration Fee \n", clean_df["registration_fee"].unique())
print("Event Duration Hours \n", clean_df["event_duration_hours"].unique())
print("Feedback Rating \n", clean_df["feedback_rating"].unique())

Gender
 <ArrowStringArray>
['other', 'male', 'unknown', 'female']
Length: 4, dtype: str
Age
 [19 21 18 24 26 27 25 22 -5 20 17 23]
Cities
 <ArrowStringArray>
[     'kochi',     'trichy',      'salem',    'chennai',  'hyderabad',
 'coimbatore',       'pune',    'unknown',     'mysuru',  'bengaluru',
    'madurai',           '',        'nan']
Length: 13, dtype: str
Department
 <ArrowStringArray>
[ 'computer science',        'mechanical',              'arts',
           'unknown',        'management', 'civil engineering',
          'commerce',       'electronics',               'nan']
Length: 9, dtype: str
Event Type
 <ArrowStringArray>
[  'sports meet',   'career fair',      'workshop', 'cultural fest',
     'hackathon',       'seminar']
Length: 6, dtype: str
Reg Channel
 <ArrowStringArray>
['email', 'website', 'mobile app', 'campus desk', 'walk-in', 'unknown', 'nan']
Length: 7, dtype: str
Payment Status
 <ArrowStringArray>
['paid', 'waived', 'refunded', 'pending', 'waive']
Length: 5, dtype: str
Attendance Status
 <ArrowStringArray>
['cancelled', 'absent', 'attended', 'registered']
Length: 4, dtype: str
Meal Pref
 <ArrowStringArray>
[    'vegetarian', 'non-vegetarian',          'vegan',        'no-meal',
        'no meal',        'unknown',               '',            'nan']
Length: 8, dtype: str
Registration Fee
 [150. 200.  nan 500. 300. 100. 250.   0. 750.]
Event Duration Hours
 [1.  2.  2.5 4.  6.  1.5 3. ]
Feedback Rating
 [3. 4. 5. 2. 1. 0.]

In [184]:
# Replacing inconsistent values and filling with mean, median and unknown. Round of feedback rating and age

clean_df['city'] = clean_df['city'].replace(['','nan'], pd.NA)
clean_df["city"] = clean_df["city"].fillna("unknown")
clean_df["department"] = clean_df["department"].replace('nan', pd.NA)
clean_df["department"] = clean_df["department"].fillna("unknown")
clean_df["registration_channel"] = clean_df["registration_channel"].replace('nan', pd.NA)
clean_df["registration_channel"] = clean_df["registration_channel"].fillna("unknown")
clean_df["payment_status"] = clean_df["payment_status"].replace('waive', 'waived')
clean_df['meal_preference'] = clean_df['meal_preference'].replace(['','nan'], pd.NA)
clean_df['meal_preference'] = clean_df['meal_preference'].replace('no meal', "no-meal")
clean_df["meal_preference"] = clean_df["meal_preference"].fillna("unknown")
clean_df["registration_fee"] = clean_df["registration_fee"].replace('nan', pd.NA)
clean_df["registration_fee"] = clean_df["registration_fee"].fillna(clean_df["registration_fee"].median())
clean_df["age"] = clean_df["age"].replace(-5, round(clean_df["age"].mean()))

In [185]:
# Checking Unique Values

print("Gender \n", clean_df["gender"].unique())
print("Age \n", clean_df["age"].unique())
print("Cities \n", clean_df["city"].unique())
print("Department \n", clean_df["department"].unique())
print("Event Type \n", clean_df["event_type"].unique())
print("Reg Channel \n", clean_df["registration_channel"].unique())
print("Payment Status \n", clean_df["payment_status"].unique())
print("Attendance Status \n", clean_df["attendance_status"].unique())
print("Meal Pref \n", clean_df["meal_preference"].unique())
print("Registration Fee \n", clean_df["registration_fee"].unique())
print("Event Duration Hours \n", clean_df["event_duration_hours"].unique())
print("Feedback Rating \n", clean_df["feedback_rating"].unique())

Gender
 <ArrowStringArray>
['other', 'male', 'unknown', 'female']
Length: 4, dtype: str
Age
 [19 21 18 24 26 27 25 22 20 17 23]
Cities
 <ArrowStringArray>
[     'kochi',     'trichy',      'salem',    'chennai',  'hyderabad',
 'coimbatore',       'pune',    'unknown',     'mysuru',  'bengaluru',
    'madurai']
Length: 11, dtype: str
Department
 <ArrowStringArray>
[ 'computer science',        'mechanical',              'arts',
           'unknown',        'management', 'civil engineering',
          'commerce',       'electronics']
Length: 8, dtype: str
Event Type
 <ArrowStringArray>
[  'sports meet',   'career fair',      'workshop', 'cultural fest',
     'hackathon',       'seminar']
Length: 6, dtype: str
Reg Channel
 <ArrowStringArray>
['email', 'website', 'mobile app', 'campus desk', 'walk-in', 'unknown']
Length: 6, dtype: str
Payment Status
 <ArrowStringArray>
['paid', 'waived', 'refunded', 'pending']
Length: 4, dtype: str
Attendance Status
 <ArrowStringArray>
['cancelled', 'absent', 'attended', 'registered']
Length: 4, dtype: str
Meal Pref
 <ArrowStringArray>
['vegetarian', 'non-vegetarian', 'vegan', 'no-meal', 'unknown']
Length: 5, dtype: str
Registration Fee
 [150. 200. 500. 300. 100. 250.   0. 750.]
Event Duration Hours
 [1.  2.  2.5 4.  6.  1.5 3. ]
Feedback Rating
 [3. 4. 5. 2. 1. 0.]

In [186]:
clean_df.isnull().sum()

student_id              0
student_name            0
gender                  0
event_date              0
age                     0
city                    0
department              0
event_type              0
registration_date       0
registration_channel    0
payment_status          0
attendance_status       0
meal_preference         0
registration_fee        0
event_duration_hours    0
feedback_rating         0
dtype: int64

In [187]:
# Checking duplicate count for first occurence

clean_df.duplicated().sum()

np.int64(37)

In [188]:
# Viewing all the duplicate rows

clean_df[clean_df.duplicated(keep=False)]

,student_id,student_name,gender,event_date,age,city,department,event_type,registration_date,registration_channel,payment_status,attendance_status,meal_preference,registration_fee,event_duration_hours,feedback_rating
118,s10999,deepa sharma,male,2026-06-04,21,pune,electronics,workshop,2026-04-14,walk-in,refunded,registered,non-vegetarian,250.0,4.0,3.0
150,s12305,keerthi rao,other,2026-07-05,18,kochi,management,seminar,2026-06-28,campus desk,waived,registered,vegetarian,200.0,2.5,3.0
206,s11749,rahul menon,other,2026-08-15,21,kochi,arts,hackathon,2026-06-19,campus desk,pending,attended,vegetarian,500.0,2.5,3.0
366,s11314,manoj kumar,male,2026-03-25,18,kochi,electronics,career fair,2026-02-17,mobile app,pending,absent,non-vegetarian,100.0,1.0,3.0
369,s11804,priya sharma,female,2026-08-06,17,mysuru,computer science,sports meet,2026-02-08,website,refunded,attended,no-meal,250.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2881,s10773,manoj kumar,female,2026-07-20,23,bengaluru,mechanical,sports meet,2026-06-06,campus desk,refunded,registered,vegetarian,250.0,2.5,4.0
2901,s12884,keerthi rao,female,2026-07-28,21,salem,civil engineering,cultural fest,2026-05-07,website,waived,absent,non-vegetarian,200.0,2.0,3.0
2970,s10291,suresh kumar,unknown,2026-02-21,21,trichy,mechanical,cultural fest,2026-02-14,website,pending,attended,vegetarian,250.0,1.5,3.0
2984,s12563,arun kumar,male,2026-04-17,22,coimbatore,commerce,cultural fest,2026-06-04,website,refunded,registered,vegetarian,0.0,6.0,3.0
2997,s10452,arun kumar,other,2026-05-14,26,coimbatore,management,hackathon,2026-04-29,email,waived,cancelled,non-vegetarian,300.0,3.0,4.0

In [189]:
# Dropping duplicate rows and resetting the index

clean_df = clean_df.drop_duplicates().reset_index(drop = True)

In [190]:
# Checking Duplicates

clean_df.duplicated().sum()

np.int64(0)

In [191]:
# Shape of raw dataset

raw_df.shape

(3000, 16)

In [192]:
# Shape of Cleaned Dataset

clean_df.shape

(2963, 16)

In [193]:
# Checking Null Value Sum of Raw Dataset

raw_df.isnull().sum()

Student ID                0
Student Name              0
Gender                   75
Event Date               16
Age                       0
City                    103
Department               58
Event Type                0
Registration Date        10
Registration Channel     88
Payment Status            0
Attendance Status         0
Meal Preference          71
Registration Fee          0
Event Duration Hours      0
Feedback Rating         146
dtype: int64

In [194]:
# Checking Null Value Sum of Cleaned Dataset

clean_df.isnull().sum()

student_id              0
student_name            0
gender                  0
event_date              0
age                     0
city                    0
department              0
event_type              0
registration_date       0
registration_channel    0
payment_status          0
attendance_status       0
meal_preference         0
registration_fee        0
event_duration_hours    0
feedback_rating         0
dtype: int64

In [195]:
# Saving the cleaned csv file

clean_df.to_csv("Atheequr_Rahaman_cleaned_university_event_registration_lab 8.csv", index = False)

In [196]:
# Checking for saved file

import os
print(os.getcwd())
print(os.path.exists("Atheequr_Rahaman_cleaned_university_event_registration_lab 8.csv"))

C:\Users\Asus\anaconda3\AI_ML_Anudip\Pandas
True