In [1]:
import pandas as pd

data = {
    "patient_name": ["Arun", "Priya", "Rahul", "Divya", "Karthik"],
    "age": [25, 26, 56, 39, 60],
    "wait_time": [15, 45, 30, 60, 10],
    "consultation_minutes": [20, 35, 25, 40, 15]
}

df = pd.DataFrame(data)
df.head()

  patient_name  age  wait_time  consultation_minutes
0         Arun   25         15                    20
1        Priya   26         45                    35
2        Rahul   56         30                    25
3        Divya   39         60                    40
4      Karthik   60         10                    15

In [2]:
# Applying a function to single column
# Increase waiting time

def add_five_mins(wait_time):
    return wait_time + 5

df["updated_wait_time"] = df["wait_time"].apply(add_five_mins)
df

  patient_name  age  wait_time  consultation_minutes  updated_wait_time
0         Arun   25         15                    20                 20
1        Priya   26         45                    35                 50
2        Rahul   56         30                    25                 35
3        Divya   39         60                    40                 65
4      Karthik   60         10                    15                 15

In [3]:
# Using lambda function with apply()

df["updated_plus"] = df["wait_time"].apply(lambda x: x+10)
df

,patient_name,age,wait_time,consultation_minutes,updated_wait_time,updated_plus
0,Arun,25,15,20,20,25
1,Priya,26,45,35,50,55
2,Rahul,56,30,25,35,40
3,Divya,39,60,40,65,70
4,Karthik,60,10,15,15,20

In [4]:
# Applying conditions using apply() function

df["updated_plus"] = df["wait_time"].apply(if wait_time > )

SyntaxError: invalid syntax (827039576.py, line 3)

In [ ]:
import pandas as pd

employee = pd.DataFrame({
    "employee_id": [101, 102, 103, 104, 105],
    "employee_name": ["Arun", "Divya", "Raghul", "Karthik", "Varun"],
    "dept": ["IT", "FN", "SL", "HR", "IT"]
})

print(employee)

In [ ]:
# dept_map = {
#     "IT" : "Information Technology"
# }

employee["dept_name"] = employee["dept"].map({
    "IT" : "Information Technology",
    "HR" : "Human Resources",
    "SL" : "Sales",
    "FN" : "Finance"
})

employee

In [5]:
employee["code_length"] = employee["dept"].map(lambda x: len(x))
employee

NameError: name 'employee' is not defined

In [6]:
df["age_group"] = df["age"].map(lambda x: "Young" if x < 50 else "Adult")
df

,patient_name,age,wait_time,consultation_minutes,updated_wait_time,updated_plus,age_group
0,Arun,25,15,20,20,25,Young
1,Priya,26,45,35,50,55,Young
2,Rahul,56,30,25,35,40,Adult
3,Divya,39,60,40,65,70,Young
4,Karthik,60,10,15,15,20,Adult

In [13]:
perf = pd.DataFrame({
    "performance": [1, 2, 3, 4]
})

perf

   performance
0            1
1            2
2            3
3            4

In [15]:
perf["definition"] = perf["performance"].map({
    1 : "Poor",
    2 : "Avg",
    3 : "Good",
    4 : "Excellent"
})

perf

   performance definition
0            1       Poor
1            2        Avg
2            3       Good
3            4  Excellent