In [ ]:
# Import the Pandas library.

import pandas as pd

In [145]:
# Load the CSV file into a DataFrame named df.

df = pd.read_csv(r"employee_productivity_lab 9.csv")
df

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
...,...,...,...,...,...,...,...,...,...,...,...,...
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [146]:
# Display the first 5 records.

df.head()

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9

In [147]:
# Check the shape of the dataset.

df.shape

(500, 12)

In [148]:
# Display the column names.

df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Location', 'Shift',
       'Work_Status', 'Priority', 'Tasks_Assigned', 'Tasks_Completed',
       'Tasks_Rejected', 'Efficiency_Percentage', 'Experience_Years'],
      dtype='str')

In [149]:
# Check the data types of all columns.

df.dtypes

Employee_ID                  str
Employee_Name                str
Department                   str
Location                     str
Shift                        str
Work_Status                  str
Priority                     str
Tasks_Assigned             int64
Tasks_Completed            int64
Tasks_Rejected             int64
Efficiency_Percentage    float64
Experience_Years           int64
dtype: object

In [150]:
# Check for missing values and duplicate records in the dataset.

print("Missing Values: \n", df.isnull().sum())
print("-"*30)
print("Duplicate Records: \n",df.duplicated().sum())

Missing Values:
 Employee_ID              0
Employee_Name            0
Department               0
Location                 0
Shift                    0
Work_Status              0
Priority                 0
Tasks_Assigned           0
Tasks_Completed          0
Tasks_Rejected           0
Efficiency_Percentage    0
Experience_Years         0
dtype: int64
------------------------------
Duplicate Records:
 0

---
# *Part A: Filtering Operations*
---

In [151]:
# 1. Single Condition Filtering

In [152]:
# 1. Filter employees whose Efficiency_Percentage is greater than 80.

df[df["Efficiency_Percentage"] > 80]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
8,EMP1009,Aishwarya R 9,Maintenance,Coimbatore,Morning,In Progress,Medium,58,58,0,100.00,5
10,EMP1011,Aravind S 11,Mechanical,Hosur,Evening,In Progress,Low,94,92,2,97.87,8
12,EMP1013,Nithya R 13,Mechanical,Coimbatore,Night,In Progress,High,149,143,3,95.97,1
18,EMP1019,Rahul Raj 19,Maintenance,Hyderabad,Morning,Pending,High,101,93,1,92.08,3
...,...,...,...,...,...,...,...,...,...,...,...,...
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
487,EMP1488,Surya Prakash 488,Mechanical,Hosur,Night,Completed,Low,150,144,3,96.00,3
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [153]:
# 2. Filter employees working in the Production department.

df[df["Department"] == "Production"]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
13,EMP1014,Keerthana S 14,Production,Chennai,Evening,In Progress,Low,68,29,5,42.65,8
16,EMP1017,Surya Prakash 17,Production,Coimbatore,Morning,In Progress,High,169,102,9,60.36,9
19,EMP1020,Sanjay Kumar 20,Production,Pune,Evening,Completed,Low,161,151,2,93.79,12
21,EMP1022,Gokul N 22,Production,Coimbatore,Night,Completed,High,56,41,0,73.21,2
...,...,...,...,...,...,...,...,...,...,...,...,...
491,EMP1492,Divya R 492,Production,Pune,Night,Pending,Medium,114,78,4,68.42,12
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [154]:
# 3. Filter employees located in Chennai.

df[df["Location"] == "Chennai"]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
9,EMP1010,Priya Sharma 10,Mechanical,Chennai,Evening,In Progress,Medium,182,130,10,71.43,2
13,EMP1014,Keerthana S 14,Production,Chennai,Evening,In Progress,Low,68,29,5,42.65,8
17,EMP1018,Lavanya M 18,Electronics,Chennai,Evening,In Progress,High,175,95,10,54.29,1
22,EMP1023,Priya Sharma 23,Electrical,Chennai,Night,Completed,Medium,55,34,2,61.82,11
...,...,...,...,...,...,...,...,...,...,...,...,...
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [155]:
# 4. Filter employees with more than 5 years of experience.

df[df["Experience_Years"] > 5]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
6,EMP1007,Meena Devi 7,Electronics,Coimbatore,Morning,In Progress,Medium,57,22,7,38.60,8
7,EMP1008,Nithya R 8,Mechanical,Hosur,Evening,Pending,Low,133,73,11,54.89,11
...,...,...,...,...,...,...,...,...,...,...,...,...
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
494,EMP1495,Divya R 495,Electrical,Hosur,Evening,Completed,High,54,32,8,59.26,12
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [156]:
# 5. Filter employees whose Work_Status is Pending.

df[df["Work_Status"] == "Pending"]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
7,EMP1008,Nithya R 8,Mechanical,Hosur,Evening,Pending,Low,133,73,11,54.89,11
14,EMP1015,Sneha Devi 15,Maintenance,Pune,Evening,Pending,Medium,175,127,0,72.57,2
18,EMP1019,Rahul Raj 19,Maintenance,Hyderabad,Morning,Pending,High,101,93,1,92.08,3
...,...,...,...,...,...,...,...,...,...,...,...,...
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [157]:
# 2. Multiple Conditions

In [158]:
# 6. Find employees from the Production department and working in the Morning shift.

df[(df["Department"] == "Production") & (df["Shift"] == "Morning")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
16,EMP1017,Surya Prakash 17,Production,Coimbatore,Morning,In Progress,High,169,102,9,60.36,9
23,EMP1024,Gokul N 24,Production,Hyderabad,Morning,In Progress,Medium,164,111,4,67.68,4
41,EMP1042,Nithya R 42,Production,Pune,Morning,In Progress,High,78,54,1,69.23,1
58,EMP1059,Priya Sharma 59,Production,Coimbatore,Morning,In Progress,High,96,42,14,43.75,8
93,EMP1094,Divya R 94,Production,Chennai,Morning,Completed,Medium,60,30,7,50.00,8
113,EMP1114,Surya Prakash 114,Production,Bengaluru,Morning,In Progress,High,166,90,4,54.22,9
124,EMP1125,Anjali Priya 125,Production,Bengaluru,Morning,Pending,High,52,51,1,98.08,10
159,EMP1160,Harish Kumar 160,Production,Chennai,Morning,Completed,Medium,118,43,7,36.44,4
176,EMP1177,Rahul Raj 177,Production,Hosur,Morning,In Progress,Medium,194,133,10,68.56,11
193,EMP1194,Rahul Raj 194,Production,Bengaluru,Morning,Pending,Low,186,159,5,85.48,9
214,EMP1215,Keerthana S 215,Production,Chennai,Morning,In Progress,Low,141,122,13,86.52,2
229,EMP1230,Priya Sharma 230,Production,Pune,Morning,In Progress,Low,133,58,12,43.61,5
233,EMP1234,Aravind S 234,Production,Bengaluru,Morning,In Progress,Low,156,95,4,60.90,12
250,EMP1251,Meena Devi 251,Production,Pune,Morning,In Progress,Medium,114,38,0,33.33,8
257,EMP1258,Nithya R 258,Production,Coimbatore,Morning,Completed,Medium,119,54,9,45.38,3
260,EMP1261,Gokul N 261,Production,Coimbatore,Morning,In Progress,Low,68,23,6,33.82,8
271,EMP1272,Karthik S 272,Production,Bengaluru,Morning,Pending,Low,178,125,1,70.22,6
273,EMP1274,Aishwarya R 274,Production,Hosur,Morning,Pending,Low,116,71,1,61.21,7
310,EMP1311,Aravind S 311,Production,Hosur,Morning,In Progress,Medium,192,129,9,67.19,3
328,EMP1329,Meena Devi 329,Production,Pune,Morning,Pending,High,130,108,5,83.08,6
334,EMP1335,Anjali Priya 335,Production,Bengaluru,Morning,In Progress,Low,114,38,8,33.33,12
338,EMP1339,Divya R 339,Production,Coimbatore,Morning,Completed,High,93,64,13,68.82,10
359,EMP1360,Nithya R 360,Production,Hosur,Morning,In Progress,High,139,131,6,94.24,1
364,EMP1365,Prakash Raj 365,Production,Pune,Morning,In Progress,Low,62,47,3,75.81,12
373,EMP1374,Rahul Raj 374,Production,Hyderabad,Morning,In Progress,High,112,71,10,63.39,5
394,EMP1395,Nithya R 395,Production,Coimbatore,Morning,Completed,High,54,50,4,92.59,11
397,EMP1398,Lavanya M 398,Production,Bengaluru,Morning,In Progress,High,76,56,6,73.68,2
398,EMP1399,Arun Kumar 399,Production,Hyderabad,Morning,In Progress,Low,54,34,7,62.96,4
438,EMP1439,Divya R 439,Production,Chennai,Morning,In Progress,Low,42,35,2,83.33,5
448,EMP1449,Gokul N 449,Production,Pune,Morning,In Progress,High,70,50,1,71.43,9
464,EMP1465,Priya Sharma 465,Production,Hyderabad,Morning,Pending,Medium,144,101,5,70.14,6
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4

In [159]:
# 7. Find employees with High Priority and whose work status is In Progress.

df[(df["Priority"] == "High") & (df["Work_Status"] == "In Progress")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
12,EMP1013,Nithya R 13,Mechanical,Coimbatore,Night,In Progress,High,149,143,3,95.97,1
16,EMP1017,Surya Prakash 17,Production,Coimbatore,Morning,In Progress,High,169,102,9,60.36,9
17,EMP1018,Lavanya M 18,Electronics,Chennai,Evening,In Progress,High,175,95,10,54.29,1
27,EMP1028,Anjali Priya 28,Mechanical,Hyderabad,Evening,In Progress,High,52,20,2,38.46,7
...,...,...,...,...,...,...,...,...,...,...,...,...
465,EMP1466,Rahul Raj 466,Electronics,Pune,Night,In Progress,High,100,20,0,20.00,2
473,EMP1474,Priya Sharma 474,Electronics,Bengaluru,Night,In Progress,High,68,46,14,67.65,12
475,EMP1476,Nithya R 476,Maintenance,Hosur,Night,In Progress,High,150,101,15,67.33,9
484,EMP1485,Deepika S 485,Mechanical,Coimbatore,Morning,In Progress,High,144,77,8,53.47,8
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1

In [160]:
# 8. Find employees who have more than 8 years of experience and efficiency greater than 70%.

df[(df["Experience_Years"] > 8) & (df["Efficiency_Percentage"] > 70)]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
19,EMP1020,Sanjay Kumar 20,Production,Pune,Evening,Completed,Low,161,151,2,93.79,12
29,EMP1030,Vignesh Kumar 30,Electrical,Coimbatore,Morning,Pending,Low,182,164,4,90.11,9
32,EMP1033,Deepika S 33,Electronics,Hyderabad,Night,Pending,Low,185,136,1,73.51,9
36,EMP1037,Meena Devi 37,Production,Hosur,Night,Completed,Low,152,141,11,92.76,9
43,EMP1044,Anjali Priya 44,Mechanical,Coimbatore,Evening,Completed,High,183,155,4,84.70,12
...,...,...,...,...,...,...,...,...,...,...,...,...
482,EMP1483,Sneha Devi 483,Maintenance,Coimbatore,Morning,In Progress,Medium,133,110,3,82.71,11
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
489,EMP1490,Prakash Raj 490,Mechanical,Coimbatore,Evening,Pending,Low,141,104,9,73.76,12
490,EMP1491,Aishwarya R 491,Maintenance,Coimbatore,Morning,Completed,Low,171,129,10,75.44,12
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [161]:
# 9. Filter employees located in Chennai or Coimbatore.

df[(df["Location"] == "Chennai") | (df["Location"] == "Coimbatore")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
6,EMP1007,Meena Devi 7,Electronics,Coimbatore,Morning,In Progress,Medium,57,22,7,38.60,8
...,...,...,...,...,...,...,...,...,...,...,...,...
490,EMP1491,Aishwarya R 491,Maintenance,Coimbatore,Morning,Completed,Low,171,129,10,75.44,12
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [162]:
# 10. Filter employees working in the Morning or Night shift.

df[(df["Shift"] == "Morning") | (df["Shift"] == "Night")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
5,EMP1006,Aishwarya R 6,Electrical,Hosur,Night,In Progress,Low,71,44,2,61.97,4
...,...,...,...,...,...,...,...,...,...,...,...,...
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [163]:
# 11. Find employees whose Work_Status is Pending or In Progress.

df[(df["Work_Status"] == "Pending") | (df["Work_Status"] == "In Progress")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
5,EMP1006,Aishwarya R 6,Electrical,Hosur,Night,In Progress,Low,71,44,2,61.97,4
6,EMP1007,Meena Devi 7,Electronics,Coimbatore,Morning,In Progress,Medium,57,22,7,38.60,8
...,...,...,...,...,...,...,...,...,...,...,...,...
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [164]:
# 12. Filter employees belonging to these departments: Production, Maintenance, Quality Control

df[df["Department"].isin(["Production", "Maintenance", "Quality Control"])]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
8,EMP1009,Aishwarya R 9,Maintenance,Coimbatore,Morning,In Progress,Medium,58,58,0,100.00,5
11,EMP1012,Anjali Priya 12,Maintenance,Pune,Night,In Progress,Low,76,36,4,47.37,10
13,EMP1014,Keerthana S 14,Production,Chennai,Evening,In Progress,Low,68,29,5,42.65,8
...,...,...,...,...,...,...,...,...,...,...,...,...
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [165]:
# 13. Filter employees located in: Chennai, Bengaluru, Hyderabad

df[df["Location"].isin(["Chennai", "Bengaluru", "Hyderabad"])]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
9,EMP1010,Priya Sharma 10,Mechanical,Chennai,Evening,In Progress,Medium,182,130,10,71.43,2
13,EMP1014,Keerthana S 14,Production,Chennai,Evening,In Progress,Low,68,29,5,42.65,8
17,EMP1018,Lavanya M 18,Electronics,Chennai,Evening,In Progress,High,175,95,10,54.29,1
...,...,...,...,...,...,...,...,...,...,...,...,...
488,EMP1489,Surya Prakash 489,Quality Control,Hyderabad,Night,Pending,High,66,44,10,66.67,5
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [166]:
# 14. Find employees whose experience is between 3 and 7 years.

df[df["Experience_Years"].between(3, 7)]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
5,EMP1006,Aishwarya R 6,Electrical,Hosur,Night,In Progress,Low,71,44,2,61.97,4
8,EMP1009,Aishwarya R 9,Maintenance,Coimbatore,Morning,In Progress,Medium,58,58,0,100.00,5
15,EMP1016,Prakash Raj 16,Electronics,Hosur,Night,In Progress,Low,115,90,5,78.26,3
18,EMP1019,Rahul Raj 19,Maintenance,Hyderabad,Morning,Pending,High,101,93,1,92.08,3
20,EMP1021,Nithya R 21,Quality Control,Pune,Evening,Completed,High,91,59,12,64.84,4
...,...,...,...,...,...,...,...,...,...,...,...,...
483,EMP1484,Nithya R 484,Maintenance,Chennai,Morning,Completed,Medium,114,104,8,91.23,3
487,EMP1488,Surya Prakash 488,Mechanical,Hosur,Night,Completed,Low,150,144,3,96.00,3
488,EMP1489,Surya Prakash 489,Quality Control,Hyderabad,Night,Pending,High,66,44,10,66.67,5
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4

In [167]:
# 15. Find employees whose efficiency percentage is between 60 and 80.

df[df["Efficiency_Percentage"].between(60, 80)]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
5,EMP1006,Aishwarya R 6,Electrical,Hosur,Night,In Progress,Low,71,44,2,61.97,4
9,EMP1010,Priya Sharma 10,Mechanical,Chennai,Evening,In Progress,Medium,182,130,10,71.43,2
14,EMP1015,Sneha Devi 15,Maintenance,Pune,Evening,Pending,Medium,175,127,0,72.57,2
...,...,...,...,...,...,...,...,...,...,...,...,...
490,EMP1491,Aishwarya R 491,Maintenance,Coimbatore,Morning,Completed,Low,171,129,10,75.44,12
491,EMP1492,Divya R 492,Production,Pune,Night,Pending,Medium,114,78,4,68.42,12
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4
499,EMP1500,Divya R 500,Maintenance,Chennai,Morning,Completed,Low,89,57,14,64.04,9

In [168]:
# 16. Filter employees whose names start with "A".

df[df["Employee_Name"].str.startswith("A")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
5,EMP1006,Aishwarya R 6,Electrical,Hosur,Night,In Progress,Low,71,44,2,61.97,4
8,EMP1009,Aishwarya R 9,Maintenance,Coimbatore,Morning,In Progress,Medium,58,58,0,100.00,5
...,...,...,...,...,...,...,...,...,...,...,...,...
490,EMP1491,Aishwarya R 491,Maintenance,Coimbatore,Morning,Completed,Low,171,129,10,75.44,12
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1
497,EMP1498,Aravind S 498,Production,Chennai,Morning,Pending,Medium,137,106,13,77.37,4

In [169]:
# 17. Filter employees whose names contain "Priya".

df[df["Employee_Name"].str.contains("Priya")]

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
1,EMP1002,Priya Sharma 2,Electronics,Chennai,Morning,Completed,Low,179,110,13,61.45,10
9,EMP1010,Priya Sharma 10,Mechanical,Chennai,Evening,In Progress,Medium,182,130,10,71.43,2
11,EMP1012,Anjali Priya 12,Maintenance,Pune,Night,In Progress,Low,76,36,4,47.37,10
22,EMP1023,Priya Sharma 23,Electrical,Chennai,Night,Completed,Medium,55,34,2,61.82,11
27,EMP1028,Anjali Priya 28,Mechanical,Hyderabad,Evening,In Progress,High,52,20,2,38.46,7
30,EMP1031,Priya Sharma 31,Production,Hyderabad,Night,Pending,High,55,40,1,72.73,1
43,EMP1044,Anjali Priya 44,Mechanical,Coimbatore,Evening,Completed,High,183,155,4,84.70,12
55,EMP1056,Anjali Priya 56,Maintenance,Bengaluru,Morning,Completed,High,198,160,2,80.81,1
57,EMP1058,Anjali Priya 58,Mechanical,Hosur,Night,Completed,High,138,121,12,87.68,7
58,EMP1059,Priya Sharma 59,Production,Coimbatore,Morning,In Progress,High,96,42,14,43.75,8
70,EMP1071,Anjali Priya 71,Maintenance,Chennai,Night,Completed,High,178,104,11,58.43,4
71,EMP1072,Anjali Priya 72,Mechanical,Hyderabad,Night,Completed,Low,91,22,4,24.18,4
74,EMP1075,Anjali Priya 75,Electronics,Hosur,Evening,Pending,Low,59,57,2,96.61,2
81,EMP1082,Anjali Priya 82,Maintenance,Hyderabad,Evening,Pending,High,172,116,2,67.44,12
91,EMP1092,Anjali Priya 92,Production,Hyderabad,Evening,In Progress,Medium,195,191,4,97.95,10
94,EMP1095,Priya Sharma 95,Mechanical,Bengaluru,Night,In Progress,Low,192,172,9,89.58,8
104,EMP1105,Priya Sharma 105,Mechanical,Pune,Evening,Pending,Medium,178,157,13,88.20,11
120,EMP1121,Anjali Priya 121,Quality Control,Hosur,Evening,In Progress,Medium,167,161,1,96.41,11
124,EMP1125,Anjali Priya 125,Production,Bengaluru,Morning,Pending,High,52,51,1,98.08,10
125,EMP1126,Priya Sharma 126,Electrical,Hyderabad,Morning,Pending,Medium,104,41,3,39.42,12
132,EMP1133,Priya Sharma 133,Electrical,Hyderabad,Morning,Completed,High,69,28,1,40.58,9
151,EMP1152,Anjali Priya 152,Electronics,Bengaluru,Night,In Progress,High,94,39,15,41.49,5
156,EMP1157,Priya Sharma 157,Mechanical,Coimbatore,Night,Completed,Low,123,115,1,93.50,2
162,EMP1163,Priya Sharma 163,Quality Control,Chennai,Evening,Completed,Medium,58,45,13,77.59,10
173,EMP1174,Priya Sharma 174,Mechanical,Hosur,Evening,In Progress,Low,61,52,2,85.25,9
179,EMP1180,Anjali Priya 180,Mechanical,Coimbatore,Morning,In Progress,High,127,109,6,85.83,9
181,EMP1182,Priya Sharma 182,Quality Control,Bengaluru,Night,Pending,High,86,41,14,47.67,8
182,EMP1183,Anjali Priya 183,Production,Coimbatore,Evening,In Progress,High,196,152,14,77.55,6
184,EMP1185,Priya Sharma 185,Maintenance,Hyderabad,Evening,Pending,High,194,131,8,67.53,12
188,EMP1189,Priya Sharma 189,Electrical,Hyderabad,Night,Completed,Low,125,63,4,50.40,8
196,EMP1197,Priya Sharma 197,Electrical,Pune,Evening,Pending,High,188,150,4,79.79,11
229,EMP1230,Priya Sharma 230,Production,Pune,Morning,In Progress,Low,133,58,12,43.61,5
232,EMP1233,Priya Sharma 233,Electronics,Coimbatore,Night,In Progress,Medium,170,141,1,82.94,9
239,EMP1240,Priya Sharma 240,Maintenance,Coimbatore,Night,Completed,Low,92,72,15,78.26,6
246,EMP1247,Priya Sharma 247,Electronics,Hyderabad,Evening,Pending,Medium,175,123,7,70.29,2
270,EMP1271,Priya Sharma 271,Mechanical,Hosur,Morning,In Progress,Medium,48,34,9,70.83,4
272,EMP1273,Anjali Priya 273,Electrical,Coimbatore,Night,Pending,High,187,183,2,97.86,7
276,EMP1277,Priya Sharma 277,Production,Hyderabad,Evening,Pending,Low,116,54,14,46.55,3
280,EMP1281,Anjali Priya 281,Maintenance,Pune,Night,Completed,Medium,70,67,3,95.71,4
291,EMP1292,Anjali Priya 292,Mechanical,Pune,Night,In Progress,Medium,64,53,2,82.81,5
296,EMP1297,Priya Sharma 297,Mechanical,Bengaluru,Morning,Completed,Low,111,100,9,90.09,3
300,EMP1301,Anjali Priya 301,Electrical,Pune,Evening,In Progress,High,109,86,15,78.90,11
334,EMP1335,Anjali Priya 335,Production,Bengaluru,Morning,In Progress,Low,114,38,8,33.33,12
348,EMP1349,Priya Sharma 349,Quality Control,Hosur,Evening,Pending,Low,61,43,5,70.49,4
368,EMP1369,Priya Sharma 369,Quality Control,Pune,Morning,In Progress,High,167,145,11,86.83,5
371,EMP1372,Anjali Priya 372,Quality Control,Hosur,Evening,In Progress,High,147,95,10,64.63,10
377,EMP1378,Priya Sharma 378,Mechanical,Hosur,Evening,Completed,High,100,73,15,73.00,4
388,EMP1389,Priya Sharma 389,Mechanical,Pune,Evening,Pending,Medium,71,22,14,30.99,8
395,EMP1396,Anjali Priya 396,Production,Hyderabad,Evening,Completed,High,101,55,1,54.46,4
402,EMP1403,Anjali Priya 403,Maintenance,Pune,Morning,In Progress,Medium,121,63,11,52.07,12
407,EMP1408,Priya Sharma 408,Quality Control,Hyderabad,Night,In Progress,High,67,66,0,98.51,7
418,EMP1419,Anjali Priya 419,Electrical,Pune,Morning,Completed,Low,152,131,8,86.18,11
427,EMP1428,Priya Sharma 428,Mechanical,Bengaluru,Evening,Completed,Low,186,183,3,98.39,10
454,EMP1455,Anjali Priya 455,Mechanical,Hosur,Evening,In Progress,High,88,22,0,25.00,2
459,EMP1460,Priya Sharma 460,Production,Chennai,Night,Completed,Low,105,93,9,88.57,1
464,EMP1465,Priya Sharma 465,Production,Hyderabad,Morning,Pending,Medium,144,101,5,70.14,6
467,EMP1468,Priya Sharma 468,Electrical,Bengaluru,Night,In Progress,Medium,52,26,5,50.00,12
473,EMP1474,Priya Sharma 474,Electronics,Bengaluru,Night,In Progress,High,68,46,14,67.65,12
496,EMP1497,Anjali Priya 497,Production,Hosur,Evening,Pending,Low,97,91,3,93.81,1

In [170]:
# 18. Use the query() method to find employees with: Efficiency_Percentage greater than 75, Experience_Years greater than 5

df.query("Efficiency_Percentage > 75 and Experience_Years > 5")

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
10,EMP1011,Aravind S 11,Mechanical,Hosur,Evening,In Progress,Low,94,92,2,97.87,8
19,EMP1020,Sanjay Kumar 20,Production,Pune,Evening,Completed,Low,161,151,2,93.79,12
29,EMP1030,Vignesh Kumar 30,Electrical,Coimbatore,Morning,Pending,Low,182,164,4,90.11,9
36,EMP1037,Meena Devi 37,Production,Hosur,Night,Completed,Low,152,141,11,92.76,9
38,EMP1039,Aravind S 39,Mechanical,Hosur,Night,In Progress,Low,112,109,1,97.32,8
...,...,...,...,...,...,...,...,...,...,...,...,...
482,EMP1483,Sneha Devi 483,Maintenance,Coimbatore,Morning,In Progress,Medium,133,110,3,82.71,11
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
490,EMP1491,Aishwarya R 491,Maintenance,Coimbatore,Morning,Completed,Low,171,129,10,75.44,12
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [171]:
# 19. Use query() to filter employees from Chennai with High priority.

df.query("Priority == 'High' and Location == 'Chennai'")

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
17,EMP1018,Lavanya M 18,Electronics,Chennai,Evening,In Progress,High,175,95,10,54.29,1
37,EMP1038,Sanjay Kumar 38,Electronics,Chennai,Night,Pending,High,116,49,4,42.24,5
39,EMP1040,Keerthana S 40,Electrical,Chennai,Morning,In Progress,High,104,30,2,28.85,11
70,EMP1071,Anjali Priya 71,Maintenance,Chennai,Night,Completed,High,178,104,11,58.43,4
78,EMP1079,Aravind S 79,Mechanical,Chennai,Evening,In Progress,High,151,146,2,96.69,8
79,EMP1080,Harish Kumar 80,Electrical,Chennai,Evening,In Progress,High,185,183,2,98.92,8
92,EMP1093,Deepika S 93,Maintenance,Chennai,Morning,Pending,High,149,108,1,72.48,5
178,EMP1179,Surya Prakash 179,Electrical,Chennai,Evening,In Progress,High,174,105,13,60.34,4
201,EMP1202,Surya Prakash 202,Electrical,Chennai,Night,In Progress,High,167,150,11,89.82,7
249,EMP1250,Keerthana S 250,Mechanical,Chennai,Evening,In Progress,High,49,49,0,100.00,12
261,EMP1262,Gokul N 262,Quality Control,Chennai,Night,In Progress,High,69,63,1,91.30,8
264,EMP1265,Rahul Raj 265,Quality Control,Chennai,Evening,In Progress,High,128,56,1,43.75,3
287,EMP1288,Rahul Raj 288,Maintenance,Chennai,Morning,In Progress,High,178,105,1,58.99,11
304,EMP1305,Sneha Devi 305,Electronics,Chennai,Evening,Pending,High,182,167,13,91.76,10
340,EMP1341,Karthik S 341,Quality Control,Chennai,Evening,Pending,High,186,140,3,75.27,12
354,EMP1355,Prakash Raj 355,Mechanical,Chennai,Morning,Completed,High,145,143,2,98.62,10
362,EMP1363,Rahul Raj 363,Electrical,Chennai,Night,Completed,High,197,136,8,69.04,9
436,EMP1437,Rahul Raj 437,Electrical,Chennai,Evening,Completed,High,128,68,8,53.12,10
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1

---
# *Part B: Sorting Operations*
---

In [172]:
# 1. Sorting Numerical Columns

In [173]:
# 20. Sort employees by Efficiency_Percentage in ascending order.

df.sort_values("Efficiency_Percentage")

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
465,EMP1466,Rahul Raj 466,Electronics,Pune,Night,In Progress,High,100,20,0,20.00,2
267,EMP1268,Meena Devi 268,Quality Control,Hosur,Night,Pending,Medium,97,20,0,20.62,9
71,EMP1072,Anjali Priya 72,Mechanical,Hyderabad,Night,Completed,Low,91,22,4,24.18,4
454,EMP1455,Anjali Priya 455,Mechanical,Hosur,Evening,In Progress,High,88,22,0,25.00,2
238,EMP1239,Vignesh Kumar 239,Electronics,Hyderabad,Evening,In Progress,High,102,26,3,25.49,7
...,...,...,...,...,...,...,...,...,...,...,...,...
324,EMP1325,Divya R 325,Maintenance,Hosur,Evening,In Progress,High,143,143,0,100.00,12
342,EMP1343,Harish Kumar 343,Quality Control,Chennai,Night,Completed,Medium,108,108,0,100.00,9
8,EMP1009,Aishwarya R 9,Maintenance,Coimbatore,Morning,In Progress,Medium,58,58,0,100.00,5
200,EMP1201,Keerthana S 201,Quality Control,Hosur,Evening,In Progress,Medium,71,71,0,100.00,3
96,EMP1097,Karthik S 97,Electronics,Chennai,Morning,In Progress,Low,78,78,0,100.00,12

In [174]:
# 21. Sort employees by Efficiency_Percentage in descending order.

df.sort_values("Efficiency_Percentage", ascending = False)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
324,EMP1325,Divya R 325,Maintenance,Hosur,Evening,In Progress,High,143,143,0,100.00,12
342,EMP1343,Harish Kumar 343,Quality Control,Chennai,Night,Completed,Medium,108,108,0,100.00,9
200,EMP1201,Keerthana S 201,Quality Control,Hosur,Evening,In Progress,Medium,71,71,0,100.00,3
249,EMP1250,Keerthana S 250,Mechanical,Chennai,Evening,In Progress,High,49,49,0,100.00,12
294,EMP1295,Rahul Raj 295,Quality Control,Hyderabad,Night,In Progress,Low,42,42,0,100.00,2
...,...,...,...,...,...,...,...,...,...,...,...,...
238,EMP1239,Vignesh Kumar 239,Electronics,Hyderabad,Evening,In Progress,High,102,26,3,25.49,7
454,EMP1455,Anjali Priya 455,Mechanical,Hosur,Evening,In Progress,High,88,22,0,25.00,2
71,EMP1072,Anjali Priya 72,Mechanical,Hyderabad,Night,Completed,Low,91,22,4,24.18,4
267,EMP1268,Meena Devi 268,Quality Control,Hosur,Night,Pending,Medium,97,20,0,20.62,9
465,EMP1466,Rahul Raj 466,Electronics,Pune,Night,In Progress,High,100,20,0,20.00,2

In [175]:
# 22. Display the Top 10 employees with the highest efficiency.

df.sort_values("Efficiency_Percentage", ascending = False).head(10)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
324,EMP1325,Divya R 325,Maintenance,Hosur,Evening,In Progress,High,143,143,0,100.00,12
342,EMP1343,Harish Kumar 343,Quality Control,Chennai,Night,Completed,Medium,108,108,0,100.00,9
200,EMP1201,Keerthana S 201,Quality Control,Hosur,Evening,In Progress,Medium,71,71,0,100.00,3
249,EMP1250,Keerthana S 250,Mechanical,Chennai,Evening,In Progress,High,49,49,0,100.00,12
294,EMP1295,Rahul Raj 295,Quality Control,Hyderabad,Night,In Progress,Low,42,42,0,100.00,2
96,EMP1097,Karthik S 97,Electronics,Chennai,Morning,In Progress,Low,78,78,0,100.00,12
8,EMP1009,Aishwarya R 9,Maintenance,Coimbatore,Morning,In Progress,Medium,58,58,0,100.00,5
440,EMP1441,Gokul N 441,Electronics,Chennai,Night,Pending,Medium,173,172,1,99.42,9
469,EMP1470,Rahul Raj 470,Electrical,Bengaluru,Morning,Completed,Medium,152,151,1,99.34,7
191,EMP1192,Rahul Raj 192,Electronics,Hyderabad,Night,Pending,High,147,146,1,99.32,11

In [176]:
# 23. Sort employees based on Experience_Years from highest to lowest.
    
df.sort_values("Experience_Years", ascending = False)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
489,EMP1490,Prakash Raj 490,Mechanical,Coimbatore,Evening,Pending,Low,141,104,9,73.76,12
0,EMP1001,Anjali Priya 1,Mechanical,Coimbatore,Night,Completed,Low,68,21,8,30.88,12
279,EMP1280,Vignesh Kumar 280,Electrical,Bengaluru,Morning,Completed,High,88,47,15,53.41,12
285,EMP1286,Aishwarya R 286,Maintenance,Hosur,Evening,In Progress,Medium,185,136,15,73.51,12
233,EMP1234,Aravind S 234,Production,Bengaluru,Morning,In Progress,Low,156,95,4,60.90,12
...,...,...,...,...,...,...,...,...,...,...,...,...
55,EMP1056,Anjali Priya 56,Maintenance,Bengaluru,Morning,Completed,High,198,160,2,80.81,1
459,EMP1460,Priya Sharma 460,Production,Chennai,Night,Completed,Low,105,93,9,88.57,1
41,EMP1042,Nithya R 42,Production,Pune,Morning,In Progress,High,78,54,1,69.23,1
30,EMP1031,Priya Sharma 31,Production,Hyderabad,Night,Pending,High,55,40,1,72.73,1
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1

In [177]:
# 24. Sort employees based on Tasks_Completed in descending order.

df.sort_values("Tasks_Completed", ascending = False)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
462,EMP1463,Keerthana S 463,Electronics,Pune,Night,Pending,High,199,196,1,98.49,5
219,EMP1220,Gokul N 220,Electronics,Chennai,Morning,Completed,Low,199,196,2,98.49,10
91,EMP1092,Anjali Priya 92,Production,Hyderabad,Evening,In Progress,Medium,195,191,4,97.95,10
411,EMP1412,Arun Kumar 412,Quality Control,Hosur,Morning,Pending,Medium,192,190,1,98.96,3
441,EMP1442,Meena Devi 442,Maintenance,Chennai,Evening,Completed,Medium,192,189,2,98.44,5
...,...,...,...,...,...,...,...,...,...,...,...,...
106,EMP1107,Divya R 107,Electrical,Pune,Morning,Pending,Medium,71,21,7,29.58,2
267,EMP1268,Meena Devi 268,Quality Control,Hosur,Night,Pending,Medium,97,20,0,20.62,9
465,EMP1466,Rahul Raj 466,Electronics,Pune,Night,In Progress,High,100,20,0,20.00,2
247,EMP1248,Keerthana S 248,Maintenance,Hyderabad,Evening,Pending,High,75,20,5,26.67,5
27,EMP1028,Anjali Priya 28,Mechanical,Hyderabad,Evening,In Progress,High,52,20,2,38.46,7

In [178]:
# 2. Sorting Text Columns

In [179]:
# 25. Sort employees alphabetically based on Employee_Name.

df.sort_values("Employee_Name")

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
121,EMP1122,Aishwarya R 122,Mechanical,Chennai,Evening,In Progress,Low,42,34,4,80.95,5
152,EMP1153,Aishwarya R 153,Production,Pune,Night,Pending,Low,186,134,13,72.04,1
161,EMP1162,Aishwarya R 162,Maintenance,Coimbatore,Night,Pending,Low,84,36,12,42.86,6
211,EMP1212,Aishwarya R 212,Production,Bengaluru,Evening,Completed,Low,121,85,2,70.25,12
273,EMP1274,Aishwarya R 274,Production,Hosur,Morning,Pending,Low,116,71,1,61.21,7
...,...,...,...,...,...,...,...,...,...,...,...,...
431,EMP1432,Vignesh Kumar 432,Quality Control,Hosur,Evening,Pending,Medium,62,32,14,51.61,1
433,EMP1434,Vignesh Kumar 434,Electronics,Coimbatore,Morning,In Progress,High,47,25,6,53.19,6
437,EMP1438,Vignesh Kumar 438,Electrical,Hosur,Evening,Pending,High,94,48,7,51.06,11
463,EMP1464,Vignesh Kumar 464,Production,Coimbatore,Evening,Pending,High,69,26,15,37.68,6
85,EMP1086,Vignesh Kumar 86,Mechanical,Hosur,Evening,In Progress,Low,120,55,5,45.83,10

In [180]:
# 26. Sort employees based on Department.

df.sort_values("Department")

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
3,EMP1004,Aravind S 4,Electrical,Coimbatore,Morning,In Progress,High,80,64,13,80.00,2
5,EMP1006,Aishwarya R 6,Electrical,Hosur,Night,In Progress,Low,71,44,2,61.97,4
22,EMP1023,Priya Sharma 23,Electrical,Chennai,Night,Completed,Medium,55,34,2,61.82,11
29,EMP1030,Vignesh Kumar 30,Electrical,Coimbatore,Morning,Pending,Low,182,164,4,90.11,9
35,EMP1036,Karthik S 36,Electrical,Chennai,Morning,In Progress,Medium,177,124,8,70.06,3
...,...,...,...,...,...,...,...,...,...,...,...,...
478,EMP1479,Prakash Raj 479,Quality Control,Pune,Evening,Completed,Medium,143,93,2,65.03,8
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
488,EMP1489,Surya Prakash 489,Quality Control,Hyderabad,Night,Pending,High,66,44,10,66.67,5
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
495,EMP1496,Nithya R 496,Quality Control,Chennai,Night,Pending,Low,115,61,1,53.04,9

In [181]:
# 27. Sort employees based on Location.

df.sort_values("Location")

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
4,EMP1005,Nithya R 5,Production,Bengaluru,Morning,Pending,Medium,137,69,11,50.36,9
28,EMP1029,Arun Kumar 29,Quality Control,Bengaluru,Evening,In Progress,Medium,55,30,12,54.55,12
33,EMP1034,Aravind S 34,Mechanical,Bengaluru,Evening,Completed,Low,120,73,6,60.83,11
46,EMP1047,Rahul Raj 47,Electrical,Bengaluru,Night,Pending,Medium,142,104,8,73.24,11
50,EMP1051,Rahul Raj 51,Maintenance,Bengaluru,Night,In Progress,Low,90,66,13,73.33,2
...,...,...,...,...,...,...,...,...,...,...,...,...
478,EMP1479,Prakash Raj 479,Quality Control,Pune,Evening,Completed,Medium,143,93,2,65.03,8
481,EMP1482,Prakash Raj 482,Electrical,Pune,Night,Pending,Medium,133,59,7,44.36,12
491,EMP1492,Divya R 492,Production,Pune,Night,Pending,Medium,114,78,4,68.42,12
492,EMP1493,Aishwarya R 493,Quality Control,Pune,Night,Pending,Low,69,68,1,98.55,7
498,EMP1499,Nithya R 499,Production,Pune,Night,Pending,High,198,174,7,87.88,12

In [182]:
# 3. Sorting Multiple Columns

In [183]:
# 28. Sort employees first by: Department → Ascending, Experience_Years → Descending

df.sort_values(["Department", "Experience_Years"], ascending=[True, False])

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
125,EMP1126,Priya Sharma 126,Electrical,Hyderabad,Morning,Pending,Medium,104,41,3,39.42,12
243,EMP1244,Harish Kumar 244,Electrical,Coimbatore,Evening,Completed,Medium,71,56,12,78.87,12
279,EMP1280,Vignesh Kumar 280,Electrical,Bengaluru,Morning,Completed,High,88,47,15,53.41,12
322,EMP1323,Arun Kumar 323,Electrical,Hosur,Morning,Pending,High,116,41,3,35.34,12
343,EMP1344,Lavanya M 344,Electrical,Pune,Morning,Pending,High,111,78,14,70.27,12
...,...,...,...,...,...,...,...,...,...,...,...,...
390,EMP1391,Meena Devi 391,Quality Control,Hyderabad,Night,In Progress,High,78,22,7,28.21,2
2,EMP1003,Aishwarya R 3,Quality Control,Coimbatore,Evening,Pending,Medium,46,37,3,80.43,1
117,EMP1118,Sneha Devi 118,Quality Control,Coimbatore,Night,In Progress,High,63,47,3,74.60,1
169,EMP1170,Lavanya M 170,Quality Control,Hosur,Evening,In Progress,Low,78,48,2,61.54,1
431,EMP1432,Vignesh Kumar 432,Quality Control,Hosur,Evening,Pending,Medium,62,32,14,51.61,1

In [184]:
# 29. Sort employees first by: Location → Ascending, Efficiency_Percentage → Descending

df.sort_values(["Location","Efficiency_Percentage"], ascending = [True, False])

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
469,EMP1470,Rahul Raj 470,Electrical,Bengaluru,Morning,Completed,Medium,152,151,1,99.34,7
189,EMP1190,Rahul Raj 190,Electronics,Bengaluru,Morning,Completed,Low,154,152,0,98.70,12
427,EMP1428,Priya Sharma 428,Mechanical,Bengaluru,Evening,Completed,Low,186,183,3,98.39,10
241,EMP1242,Vignesh Kumar 242,Mechanical,Bengaluru,Night,In Progress,High,107,105,1,98.13,5
124,EMP1125,Anjali Priya 125,Production,Bengaluru,Morning,Pending,High,52,51,1,98.08,10
...,...,...,...,...,...,...,...,...,...,...,...,...
63,EMP1064,Keerthana S 64,Electrical,Pune,Evening,In Progress,High,94,28,13,29.79,4
106,EMP1107,Divya R 107,Electrical,Pune,Morning,Pending,Medium,71,21,7,29.58,2
299,EMP1300,Deepika S 300,Production,Pune,Evening,In Progress,High,99,29,10,29.29,11
288,EMP1289,Arun Kumar 289,Mechanical,Pune,Evening,In Progress,High,99,28,4,28.28,10
465,EMP1466,Rahul Raj 466,Electronics,Pune,Night,In Progress,High,100,20,0,20.00,2

---
# *Part C: Filtering and Sorting Together*
---

In [185]:
# 30. Find employees from the Production department and sort them by Efficiency_Percentage from highest to lowest.

df[df["Department"] == "Production"].sort_values("Efficiency_Percentage", ascending = False)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
124,EMP1125,Anjali Priya 125,Production,Bengaluru,Morning,Pending,High,52,51,1,98.08,10
91,EMP1092,Anjali Priya 92,Production,Hyderabad,Evening,In Progress,Medium,195,191,4,97.95,10
315,EMP1316,Aishwarya R 316,Production,Hosur,Evening,Pending,High,162,156,3,96.30,6
213,EMP1214,Prakash Raj 214,Production,Coimbatore,Night,Completed,High,181,174,5,96.13,5
474,EMP1475,Aravind S 475,Production,Pune,Night,Pending,Low,174,167,3,95.98,2
...,...,...,...,...,...,...,...,...,...,...,...,...
260,EMP1261,Gokul N 261,Production,Coimbatore,Morning,In Progress,Low,68,23,6,33.82,8
334,EMP1335,Anjali Priya 335,Production,Bengaluru,Morning,In Progress,Low,114,38,8,33.33,12
250,EMP1251,Meena Devi 251,Production,Pune,Morning,In Progress,Medium,114,38,0,33.33,8
144,EMP1145,Sanjay Kumar 145,Production,Hosur,Night,Pending,Low,77,24,4,31.17,6
299,EMP1300,Deepika S 300,Production,Pune,Evening,In Progress,High,99,29,10,29.29,11

In [186]:
# 31. Find employees located in Chennai and display the top 10 employees with the highest Tasks_Completed.

df[df["Location"] == "Chennai"].sort_values("Tasks_Completed", ascending=False).head(10)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
219,EMP1220,Gokul N 220,Electronics,Chennai,Morning,Completed,Low,199,196,2,98.49,10
441,EMP1442,Meena Devi 442,Maintenance,Chennai,Evening,Completed,Medium,192,189,2,98.44,5
79,EMP1080,Harish Kumar 80,Electrical,Chennai,Evening,In Progress,High,185,183,2,98.92,8
164,EMP1165,Rahul Raj 165,Quality Control,Chennai,Morning,In Progress,Low,198,176,11,88.89,7
440,EMP1441,Gokul N 441,Electronics,Chennai,Night,Pending,Medium,173,172,1,99.42,9
304,EMP1305,Sneha Devi 305,Electronics,Chennai,Evening,Pending,High,182,167,13,91.76,10
194,EMP1195,Harish Kumar 195,Quality Control,Chennai,Night,In Progress,Medium,169,159,0,94.08,5
335,EMP1336,Sneha Devi 336,Production,Chennai,Evening,Pending,Medium,166,156,8,93.98,9
486,EMP1487,Karthik S 487,Quality Control,Chennai,Night,Pending,High,157,152,4,96.82,9
140,EMP1141,Divya R 141,Electrical,Chennai,Morning,Pending,Medium,190,151,0,79.47,9

In [187]:
# 32. Find employees with High Priority and sort them by Experience_Years in descending order

df[df["Priority"] == "High"].sort_values("Experience_Years", ascending = False)

,Employee_ID,Employee_Name,Department,Location,Shift,Work_Status,Priority,Tasks_Assigned,Tasks_Completed,Tasks_Rejected,Efficiency_Percentage,Experience_Years
62,EMP1063,Karthik S 63,Mechanical,Coimbatore,Evening,Pending,High,121,110,1,90.91,12
43,EMP1044,Anjali Priya 44,Mechanical,Coimbatore,Evening,Completed,High,183,155,4,84.70,12
134,EMP1135,Sneha Devi 135,Quality Control,Pune,Evening,In Progress,High,79,76,3,96.20,12
145,EMP1146,Meena Devi 146,Quality Control,Pune,Night,In Progress,High,137,133,4,97.08,12
81,EMP1082,Anjali Priya 82,Maintenance,Hyderabad,Evening,Pending,High,172,116,2,67.44,12
...,...,...,...,...,...,...,...,...,...,...,...,...
245,EMP1246,Sneha Devi 246,Production,Hosur,Night,Completed,High,183,137,4,74.86,1
366,EMP1367,Nithya R 367,Mechanical,Hosur,Evening,Pending,High,172,125,5,72.67,1
359,EMP1360,Nithya R 360,Production,Hosur,Morning,In Progress,High,139,131,6,94.24,1
369,EMP1370,Sneha Devi 370,Mechanical,Hosur,Night,Completed,High,66,56,10,84.85,1
493,EMP1494,Arun Kumar 494,Production,Chennai,Morning,In Progress,High,176,132,13,75.00,1